<?php
    // Set default value if necessary:
    if (!isset($this->searchClassId)) {
        $config = $this->config()->get('config');
        $this->searchClassId = $config->Site->defaultSearchBackend ?? 'Solr';
    }

    // Load search actions and settings (if any):
    $options = $this->searchOptions($this->searchClassId);
    $handlers = $this->searchbox()->getHandlers(
        $this->searchClassId, $this->searchIndex ?? null
    );
    $handlerCount = count($handlers);
    $basicSearch = $this->searchbox()->combinedHandlersActive() ? 'combined-searchbox' : $options->getSearchAction();
    $searchHome = $options->getSearchHomeAction();
    $advSearch = $options->getAdvancedSearchAction();
    $lastSort = $this->searchMemory()->getLastSort($this->searchClassId);
    $lastLimit = $this->searchMemory()->getLastLimit($this->searchClassId);
    $ignoreHiddenFilterMemory = $this->ignoreHiddenFilterMemory ?? false;
    $ignoreHiddenFiltersInRequest = $this->ignoreHiddenFiltersInRequest ?? false;
    $hiddenFilters = $this->searchTabs()->getHiddenFilters($this->searchClassId, $ignoreHiddenFilterMemory, $ignoreHiddenFiltersInRequest);
    if (empty($hiddenFilters) && !$ignoreHiddenFilterMemory) {
        $hiddenFilters = $this->searchMemory()->getLastHiddenFilters($this->searchClassId);
        if (empty($hiddenFilters)) {
            $hiddenFilters = $this->searchTabs()->getHiddenFilters($this->searchClassId);
        }
    }
    $hiddenFilterParams = $this->searchTabs()->getCurrentHiddenFilterParams($this->searchClassId, $ignoreHiddenFilterMemory, '?');

    if (!isset($this->filterList) || !isset($this->checkboxFilters)) {
        $params = $this->searchMemory()->getLastSearchParams($this->searchClassId);
        $filterList = $params->getFilterList(true);
        $checkboxFilters = $params->getCheckboxFacets();
    } else {
        $filterList = is_array($this->filterList) ? $this->filterList : [];
        $checkboxFilters = is_array($this->checkboxFilters) ? $this->checkboxFilters : [];
    }
    $filterDetails = $this->searchbox()->getFilterDetails($filterList, $checkboxFilters);
    $showFilters = $filterDetails && (isset($results) || $options->getRetainFilterSetting());
?>

<?php
  $this->headScript()->appendFile('facets.js');

  // Save results/options to $this so they are available to sub-templates:
  $this->results = $results = $this->recommend->getResults();
  $this->options = $options = $results->getOptions();
  $collapsedFacets = $this->recommend->getCollapsedFacets();
  $forceUncollapsedFacets = [];

  // Make sure facets with active selections are not collapsed:
  $filterList = $results->getParams()->getFilterList(true);
  foreach ($filterList as $field => $filters) {
    foreach ($filters as $filter) {
      // @Scheel - new code
      if(isset($filter['field']) && $filter['field'] === "textbook_catalogue_hierarchical_str_mv" && (!isset($filter['operator']) || $filter['operator'] != "NOT")){ //scheel 
        $catalogueSelected = $filter['displayText'];//only one canbe selected at a time
      }
      // @Scheel - end
      $index = isset($filter['field']) ? array_search($filter['field'], $collapsedFacets) : false;
      if ($index !== false) {
        unset($collapsedFacets[$index]); // Open if we have a match
        $forceUncollapsedFacets[] = $filter['field'];
      }
    }
  }

  $hierarchicalFacets = $this->recommend->getHierarchicalFacets();
  if ($hierarchicalFacets) {
    // jstree.min.js used to be injected by hierarchical-facet.js, but with deferred
    // processing it's called too late to append anything to the headers.
    $this->headScript()->appendFile('vendor/jsTree/jstree.min.js');
  }
?>
<!--button class="close-offcanvas btn btn-link" data-toggle="offcanvas"><?=$this->transEsc('navigate_back') ?></button-->
<?php if ($results->getResultTotal() > 0): ?>
  <h2><?=$this->transEsc($this->slot('side-facet-caption')->get('Narrow Search')) ?></h2>
<?php endif; ?>

       <?php if ($showFilters): ?>

    <?=$this->context($this)->renderInContext(
      'search/filters.phtml',
      [
        'params' => $params ?? null,
        'urlQuery' => isset($results) ? $results->getUrlQuery() : null,
        'filterList' => $showFilters ? $filterList : [],
        'checkboxFilters' => $showFilters ? $checkboxFilters : [],
        'searchClassId' => $this->searchClassId,
        'searchType' => $this->searchType,
      ]
    );?>
    <?php endif ?>


<?php $checkboxFilters = $this->recommend->getCheckboxFacetSet(); ?>
<?php $checkboxesShown = false; ?>
<?php if (count($checkboxFilters) > 0):
    foreach ($checkboxFilters as $current) {
      if ($results->getResultTotal() > 0 || $current['alwaysVisible']) {
        $checkboxesShown = true;
        break;
      }
    }
  ?>
  <?php if ($checkboxesShown): ?>
    <div class="checkboxFilter">
      <?=$this->context($this)->renderInContext('Recommend/SideFacets/checkbox-filters.phtml', ['checkboxFilters' => $checkboxFilters, 'results' => $results]); ?>
    </div>
  <?php endif; ?>
<?php endif; ?>
<?= isset($this->sideFacetExtraControls) ? $this->sideFacetExtraControls : '' ?>
<?php $sideFacetSet = $this->recommend->getFacetSet(); ?>
<?php $hierarchicalFacets = $this->recommend->getHierarchicalFacets() ?>
<?php $hierarchicalFacetSortOptions = $this->recommend->getHierarchicalFacetSortOptions() ?>
<?php if (!empty($sideFacetSet) && $results->getResultTotal() > 0): ?>
  <?php foreach ($sideFacetSet as $title => $cluster): ?>
    <div class="list-group facet-group facet-group-ex" id="side-panel-<?=$this->escapeHtmlAttr($title) ?>">
      <button class="list-group-item title<?php if (in_array($title, $collapsedFacets)): ?> collapsed<?php endif ?>" data-toggle="collapse" href="#side-collapse-<?=$this->escapeHtmlAttr($title) ?>" >
        <?=$this->transEsc($cluster['label'])?>
      </button>
      <div id="side-collapse-<?=$this->escapeHtmlAttr($title) ?>" class="collapse<?php if (!in_array($title, $collapsedFacets)): ?> in<?php endif ?>"<?php if (in_array($title, $forceUncollapsedFacets)): ?> data-force-in="1"<?php endif ?>>
        <?=$this->context($this)->renderInContext(
          'Recommend/SideFacets/facet.phtml',
          [
            'facet' => $title,
            'cluster' => $cluster,
            'collapsedFacets' => $collapsedFacets
          ]
        ); ?>
      </div>
    </div>
  <?php endforeach; ?>
<?php endif; ?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, "registerMoreLessFacetsEventHandlers();", 'SET');?>
<!-- @SajadKarim - There is some more code to move from old code but I could not find any equivalent code in newer version... so need to track the chagne from SVN -->
