<?php $this->headTitle('Tutorials'); ?>
<div class="imprint">
	<h1 class="">International TextbookCat Tutorials</h1>

	<h2 class="">Funzioni base</h1>
	  <!--span id="take-tour" class="hidden-xs">&nbsp;<a href="#" class="btn btn-primary">Tour</a></span-->
	  <div>Qui vengono presentate le funzioni di base necessarie per eseguire una ricerca.</div>
	  
	  <span id="take-tour1" onclick="startBasicTour()" class="hidden-xs">&nbsp;<a href="#" class="btn btn-primary">Tour</a></span>
	  
	<h2 class="">Fatti interessanti sull'ITBC e sui suoi cataloghi</h1>
	  <div></div>
	  <span id="take-tour2" onclick="startFactsTour()" class="hidden-xs">&nbsp;<a href="#" class="btn btn-primary">Tour</a></span>

	<h2 class="">Creazione account</h1>
	  <div>Questo ti guiderà attraverso tutti i passaggi necessari per creare un account. Solo con un account puoi gestire i preferiti o salvare i risultati della ricerca.</div>
	  <span><a href="#" class="btn btn-primary">Tour</a></span>

	<h2 class="">Funzioni avanzate</h1>
	  <div>Vuoi sfruttare subito tutte le potenzialità dello strumento? Quindi puoi avere tutte le funzionalità spiegate in dettaglio.</div>
	  <span><a href="#" class="btn btn-primary">Tour</a></span>
</div>
