<footer class="hidden-print">
  <div class="footer-container">
    <div class="footer-column">
      <?php $this->slot('footer-left')->start(); ?>
        <h2><?=$this->transEsc('Search Options')?></h2>
        <ul>
          <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
          <!--  @Scheel - commeting out old code
          <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
          -->
        </ul>
      <?=$this->slot('footer-left')->end(); ?>
    </div>
    <div class="footer-column">
      <?php $this->slot('footer-center')->start(); ?>
        <h2><?=$this->transEsc('Find More')?></h2>
        <ul>
          <!--  @Scheel - commeting out old code
          <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
          <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
          <li><a href="<?=$this->url('channels-home')?>"><?=$this->transEsc('channel_explore')?></a></li>
          <li><a href="<?=$this->url('search-reserves')?>"><?=$this->transEsc('Course Reserves')?></a></li>
          <li><a href="<?=$this->url('search-newitem')?>"><?=$this->transEsc('New Items')?></a></li>
          -->
          <!-- @Scheel - new code -->
          <li><a href="http://www.gei.de/bibliothek/digitale-angebote.html"><?=$this->transEsc('Digital resources')?></a></li>
          <li><a href="https://opac.lbs-braunschweig.gbv.de/DB=6/LNG=DU/"><?=$this->transEsc('Online catalogue')?></a></li>
          <!--li><a href="#"  onClick="Lightbox.get('Gei', 'Map'); return false;" >BETA: <?=$this->transEsc('Map')?></a></li-->
          <!-- @Scheel - end -->
          </ul>
      <?=$this->slot('footer-center')->end(); ?>
    </div>
    <div class="footer-column">
      <?php $this->slot('footer-right')->start(); ?>
        <h2><?=$this->transEsc('Need Help?')?></h2>
        <ul>
          <!--  @Scheel - commeting out old code
          <li><a href="<?=$this->url('help-home')?>?topic=search&amp;_=<?=time() ?>" data-lightbox class="help-link"><?=$this->transEsc('Search Tips')?></a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'asklibrary']) ?>"><?=$this->transEsc('Ask a Librarian')?></a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'faq']) ?>"><?=$this->transEsc('FAQs')?></a></li>
          -->
          <!-- @Scheel - new code -->
          <li><a href="<?=$this->url('help-home')?>?topic=search&amp;_=<?=time() ?>" data-lightbox class="help-link"><?=$this->transEsc('Search Tips')?></a></li>
          <li><a href="mailto:bibauskunft@gei.de"><i class="fa fa-envelope"></i><?=$this->transEsc('Ask a Librarian')?></a></li>
          <li><a href="<?=$this->url('help-home')?>?topic=imprint&amp;_=<?=time() ?>" data-lightbox class="help-link"><?=$this->transEsc('Imprint')?></a></li>
          <!--li><a href="#"><?=$this->transEsc('FAQs')?></a></li-->
          <!--li> <a href="#" onClick="Lightbox.get('Gei', 'Imprint'); return false;" ><?=$this->transEsc("Imprint")?></a></li-->
          <!-- @Scheel - end -->
        </ul>
      <?=$this->slot('footer-right')->end(); ?>
    </div>
  </div>
  <!-- @Scheel - new code -->
  <script type="text/javascript" id="initTourSearchPage">
    /*<![CDATA[*/
    initTourResultPage("take-tour1");
    /*]]>*/
  </script>
  <!-- @Scheel - end -->
  <div class="poweredby">
    <?=$this->layout()->poweredBy ?>
  </div>
</footer>
