<?php $this->headTitle('Tutorials'); ?>
<div class="imprint">
	<h1 class="">International TextbookCat Tutorials</h1>

	<h2 class="">Basic functions</h1>
	  <!--span id="take-tour" class="hidden-xs">&nbsp;<a href="#" class="btn btn-primary">Tour</a></span-->
	  <div>The basic functions that are necessary to perform a search are presented here.</div>
	  
	  <span id="take-tour1" onclick="startBasicTour()" class="hidden-xs">&nbsp;<a href="#" class="btn btn-primary">Tour</a></span>
	  
	<h2 class="">Interesting facts about the ITBC and its catalogs</h1>
	  <div></div>
	  <span id="take-tour2" onclick="startFactsTour()" class="hidden-xs">&nbsp;<a href="#" class="btn btn-primary">Tour</a></span>

	<h2 class="">Account creation</h1>
	  <div>This will guide you through all the steps necessary to create an account. Only with an account you can manage favorites or save search results.</div>
	  <span><a href="#" class="btn btn-primary">Tour</a></span>

	<h2 class="">Advanced functions</h1>
	  <div>Do you want to exploit the full potential of the tool immediately? Then you can have all the features explained in detail.</div>
	  <span><a href="#" class="btn btn-primary">Tour</a></span>
</div>
