<?php $account = $this->auth()->getManager(); ?>
<div class="gei-header<?php if ($this->layout()->templateName !== 'home'): ?> gei-header--extended row<?php else: ?> gei-header--compact<?php endif; ?>">

  <?php if ($this->layout()->templateName !== 'home'): ?><div class="gei-header__logo-col col-sm-3"><?php endif; ?>
    <div class="gei-header__logo">
      <a class="gei-header__logo-link" href="<?=$this->url('home')?>">GEI</a>
    </div>
    <?php if ($this->layout()->templateName !== 'home'): ?></div><?php endif; ?>

    <button type="button" class="gei-header__toggle navbar-toggle" data-toggle="collapse" data-target="#header-collapse">
      <span class="sr-only">Toggle navigation</span>
      <i class="fa fa-bars" aria-hidden="true"></i>
    </button>

    <?php if ($this->layout()->templateName !== 'home'): ?>
      <section class="gei-header__searchbox visible-lg col-sm-6">
        <?=$this->layout()->searchbox ?>
      </section>
    <?php endif; ?>
    <?php if (!isset($this->layout()->renderingError)): ?>
      <div class="gei-header__tools col-sm-3">
        <div class="collapse navbar-collapse" id="header-collapse">
          <nav>
            <ul role="navigation" class="nav navbar-nav navbar-right flip">
              <!-- @SajadKarim - Does not exist in the templated.
              <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>-->
              <?php if ($this->feedback()->tabEnabled()): ?>
                <li>
                  <a id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope" aria-hidden="true"></i> <?=$this->transEsc("Feedback")?></a>
                </li>
              <?php endif; ?>
              <?php $cart = $this->cart(); if ($cart->isActive()): ?>
              <li id="cartSummary">
                <a id="cartItems" data-lightbox title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>">
                  
                </a>
              </li>
            <?php endif; ?>
            <?php if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
              <li class="logoutOptions<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
                <a href="<?=$this->url('myresearch-home', array(), array('query' => array('redirect' => 0)))?>"><i class="fa fa-home" aria-hidden="true"></i> <?=$this->transEsc("Your Account")?></a>
              </li>
              <li class="logoutOptions<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
                <a href="<?=$this->url('myresearch-logout')?>" class="logout"><i class="fa fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?></a>
              </li>
              <!-- @SajadKarim - Does not exist in the templated.
              <li id="loginOptions"<?php if($account->isLoggedIn()): ?> class="hidden"<?php endif ?>>
                <?php if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                  <a href="<?=$this->url('myresearch-userlogin')?>"><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Institutional Login")?></a>
                <?php else: ?>
                  <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Login")?></a>
                <?php endif; ?>
              </li>
              -->
            <?php endif; ?>

            <?php if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
              <li class="theme dropdown">
                <form method="post" name="themeForm" id="themeForm">
                  <input type="hidden" name="ui"/>
                </form>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <?php foreach ($this->layout()->themeOptions as $current): ?>
                    <li<?=$current['selected'] ? ' class="active"' : ''?>><a href="#" onClick="document.themeForm.ui.value='<?=$this->escapeHtmlAttr($current['name'])?>';document.themeForm.submit()"><?=$this->transEsc($current['desc'])?></a></li>
                  <?php endforeach; ?>
                </ul>
              </li>
            <?php endif; ?>

            <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
              <li class="language dropdown">
                <form method="post" name="langForm" id="langForm">
                  <input type="hidden" name="mylang"/>
                </form>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <?php foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                    <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()"><?=$this->displayLanguageOption($langName)?></a></li>
                  <?php endforeach; ?>
                </ul>
              </li>
            <?php endif; ?>
          </ul>
        </nav>
      </div>
    </div>
  <?php endif; ?>
</div>
