<?php
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  $this->layout()->breadcrumbs = false;
?>

<!-- @Scheel - old code
<div class="searchHomeContent">
-->
<!-- @Scheel - new code -->
<div class="searchHomeContent col-sm-3">
<h2><?=$this->transEsc('Text filtering')?></h2>
<div class="well well-lg clearfix" role="search">
<!-- @Scheel - end -->
  <?php $this->slot('search-home-hero')->start() ?>
    <?=$this->context($this)->renderInContext("search/searchbox.phtml", ['ignoreHiddenFilterMemory' => true])?>
    <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$("#searchForm_lookfor").focus();', 'SET'); ?>
  <?=$this->slot('search-home')->end() ?>
</div>
</div>

<?=implode('', array_map([$this, 'contentBlock'], $blocks ?? []))?>
<!-- @SajadKarim - There is some more code to move from old code but I could not find any equivalent code in newer version... so need to track the chagne from SVN -->

