<?php

//$this->headLink()->appendStylesheet('bootstrap-tour-standalone.min.css');
//$this->headScript()->appendFile("bootstrap-tour-standalone.min.js");

?>
<script type="text/javascript">
// Instance the tour
var tour = new Tour({
  steps: [
  {
    element: "#searchForm_lookfor",
    title: "<?=$this->transEsc('tour_step1_title')?>",
    content: "<?=$this->transEsc('tour_step1_content')?>",
    placement: 'top',
    path: "/gei/"
  },
  {
    element: "#searchForm_type",
    title: "<?=$this->transEsc('tour_step2_title')?>",
    content: "<?=$this->transEsc('tour_step2_content')?>",
    placement: 'top',
    path: "/gei/"
  },
  {
    element: "#searchForm_searchBtn",
    title: "<?=$this->transEsc('tour_step3_title')?>",
    content: "<?=$this->transEsc('tour_step3_content')?>",
    placement: 'top',
    path: "/gei/"
  },
  {
    element: "#facet_textbook_catalogue_hierarchical_str_mv_container",
    title: "<?=$this->transEsc('tour_step4_title')?>",
    content: "<?=$this->transEsc('tour_step4_content')?>",
    placement: 'top',
    path: "/gei/"
  },
  {
    element: "#sort_options_1",
    title: "<?=$this->transEsc('tour_step5_title')?>",
    content: "<?=$this->transEsc('tour_step5_content')?>",
    //placement: 'top'
    path: '/gei/Search/Results?lookfor=&type=AllFields&limit=20'
  }]
    ,storage: window.localStorage

  });
	  
function start_demo(){
	//window.localStorage.clear();
	//tour.setCurrentStep(1);

  // Start the tour
  tour.restart();
}

$(document).ready(function() {
  // Initialize the tour
  tour.init();

	$("#btnDemoLaunch").bind("click", start_demo);
})
</script>
