<?php
  // Set up some convenience variables:
  $id = $this->driver->getUniqueId();
  $source = $this->driver->getSourceIdentifier();
  if (isset($this->list) && is_object($this->list)) {
    $list_id = $this->list->id;
    $user_id = $this->list->user_id;
  } else {
    $list_id = null;
    $user_id = $this->user ? $this->user->id : null;
  }
  // Thumbnail
  $coverDetails = $this->record($this->driver)->getCoverDetails('list-entry', 'medium', $this->recordLink()->getUrl($this->driver));
  $cover = $coverDetails['html'];
  $thumbnail = false;
  $thumbnailAlignment = $this->record($this->driver)->getThumbnailAlignment('list');
  if ($cover):
    ob_start(); ?>
    <div class="media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?>">
      <?=$cover ?>
    </div>
    <?php $thumbnail = ob_get_contents(); ?>
  <?php ob_end_clean(); ?>
<?php endif; ?>
<!-- @Scheel - old code
<div class="result<?php if($this->driver->supportsAjaxStatus()): ?> ajaxItem<?php endif ?>">
-->
<!-- @Scheel - new code -->
<div class="edu-teaser edu_rv-teaser clearfix  result<?php if($this->driver->supportsAjaxStatus()): ?> ajaxItem<?php endif ?>">
<!-- @Scheel - end -->
  <input type="hidden" value="<?=$this->escapeHtmlAttr($id) ?>" class="hiddenId"/>
  <input type="hidden" value="<?=$this->escapeHtmlAttr($source) ?>" class="hiddenSource"/>
  <?=$this->record($this->driver)->getCheckbox()?>
  <div class="media">
    <?php if ($thumbnail && $thumbnailAlignment == 'left'): ?>
      <?=$thumbnail ?>
    <?php endif; ?>
    <div class="media-body">
      <div class="result-body">
        <div class="resultItemLine1">
          <?php $missing = $this->driver instanceof \VuFind\RecordDriver\Missing; ?>
          <?php if (!$missing): ?><a href="<?=$this->recordLink()->getUrl($this->driver)?>" class="getFull" data-view="<?=$this->params->getOptions()->getListViewOption() ?>"><?php endif; ?>
            <!-- @Scheel - old code
            <span class="title"><?=$this->record($this->driver)->getTitleHtml()?></span>
            -->
            <!-- @Scheel - new code -->
            <span class="edu-link"><?=$this->record($this->driver)->getTitleHtml()?></span>
            <!-- @Scheel - end -->
          <?php if (!$missing): ?></a><?php endif; ?>
        </div>

        <div class="resultItemLine2">
          <?php if($this->driver->isCollection()): ?>
            <?=implode('<br>', array_map([$this, 'escapeHtml'], $this->driver->getSummary())); ?>
          <?php else: ?>
            <?php $summAuthors = $this->driver->getPrimaryAuthors(); if (!empty($summAuthors)): ?>
              <!-- @Scheel - old code
              <?=$this->transEsc('by')?>
              <?php $authorCount = count($summAuthors); foreach ($summAuthors as $i => $summAuthor): ?>
                <a href="<?=$this->record($this->driver)->getLink('author', $summAuthor)?>"><?=$this->escapeHtml($summAuthor)?></a><?=($i + 1 < $authorCount ? ';' : '') ?>
              <?php endforeach; ?>
              -->
              <!-- @Scheel - new code -->
              <div class="res-left">
                <?=$this->transEsc('by')?>
              </div>
              <div class="res-right">
                <?php $authorCount = count($summAuthors); foreach ($summAuthors as $i => $summAuthor): ?>
                  <a href="<?=$this->record($this->driver)->getLink('author', $summAuthor)?>"><?=$this->escapeHtml($summAuthor)?></a><?=($i + 1 < $authorCount ? ';' : '') ?>
                <?php endforeach; ?>
              </div>
              <!-- @Scheel - end -->
            <?php endif; ?>
            <!-- @Scheel - new code -->
            <?php $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
            <div class="res-left"><?=$this->transEsc('Published')?></div>
            <div class="res-right">
              <?php foreach ($publications as $field): ?>
              <span property="publisher" typeof="Organization">
              <?php $pubPlace = $field->getPlace(); $pubName = $field->getName(); $pubDate = $field->getDate(); ?>
              <?php if (!empty($pubPlace)): ?>
                <?php foreach ($pubPlace as $pp): ?><!--
                --><?php if ($pp!=$pubPlace[0]): ?><span>, </span><?php endif; ?><!--
                --><a property="location" href="<?=$this->record($this->driver)->getLink('pubPlace', $pp)?>"><?=$this->escapeHtml($pp)?></a><!--
                --><?php endforeach; ?><!--
                --><span><?=(!empty($pubName))?':':((!empty($pubDate))?',':'')?></span>
              <?php endif; ?>
              <?php if (!empty($pubName)): ?>
                <?php foreach ($pubName as $pn): ?><!--
                --><?php if ($pn!=$pubName[0]): ?><span>, </span><?php endif; ?><!--
                --><a property="name" href="<?=$this->record($this->driver)->getLink('pubName', $pn)?>"><?=$this->escapeHtml($pn)?></a><!--
                --><?php endforeach; ?><!--
                --><span><?=(!empty($pubDate))?',':''?></span>
              <?php endif; ?>
              </span>
              <?php if (!empty($pubDate)): ?>
                <?php foreach ($pubDate as $pd): ?>
                <?php if ($pd!=$pubDate[0]): ?><span>, </span><?php endif; ?>
                <span property="publicationDate"><?=$this->escapeHtml($pd)?></span>
                <?php endforeach; ?>
              <?php endif; ?>
              <?php break;/*scheel: show only one*/ ?>
              <?php endforeach; ?>
            </div>
            <?php endif; ?>
            
            
            <?php $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
            <div class="res-left"><?=$this->transEsc('Edition')?></div>
            <div class="res-right"><?=$this->escapeHtml($edition)?></div>
            <?php endif; ?>

            <?/* Display series section if at least one series exists. */?>
            <?php $series = $this->driver->getSeries(); if (!empty($series)): ?>
            <div class="res-left"><?=$this->transEsc('Series')?></div>
            <div class="res-right">
              <?php foreach ($series as $field): ?>
              <?/*scheel: if not first entry: indent*/?>
              <?php if ($series[0]!=$field): ?>
                </div><div class="res-left">&nbsp;</div><div class="res-right">
              <?php endif; ?>
              
              <?/* Depending on the record driver, $field may either be an array with
                "name" and "number" keys or a flat string containing only the series
                name.  We should account for both cases to maximize compatibility. */?>
              <?php if (is_array($field)): ?>
                <?php if (!empty($field['name'])): ?>
                <a href="<?=$this->record($this->driver)->getLink('series', $field['name'])?>"><?=$this->escapeHtml($field['name'])?></a>
                <?php if (!empty($field['number'])): ?>
                  <?=$this->escapeHtml($field['number'])?>
                <?php endif; ?>
                <br/>
                <?php endif; ?>
              <?php else: ?>
                <a href="<?=$this->record($this->driver)->getLink('series', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
              <?php endif; ?>
              <?php endforeach; ?>
            </div>
            <?php endif; ?>
            <!-- @Scheel - end -->
            <!-- @Scheel - old code
            <?php $journalTitle = $this->driver->getContainerTitle(); $summDate = $this->driver->getPublicationDates(); ?>
             -->
             <?php if (!empty($journalTitle)): ?>
              <!-- @Scheel - old code
              <?=!empty($summAuthor) ? '<br/>' : ''?>
              <?=/* TODO: handle highlighting more elegantly here */ $this->transEsc('Published in') . ' <a href="' . $this->record($this->driver)->getLink('journaltitle', str_replace(['{{{{START_HILITE}}}}', '{{{{END_HILITE}}}}'], '', $journalTitle)) . '">' . $this->highlight($journalTitle) . '</a>';?>
              <?=!empty($summDate) ? ' (' . $this->escapeHtml($summDate[0]) . ')' : ''?>
              -->
              <!-- @Scheel - new code -->
              <div class="res-left">
                <?=$this->transEsc('Published in')?>
              </div>
              <div class="res-right">
                <?=/* TODO: handle highlighting more elegantly here */ $this->transEsc('Published in') . ' <a href="' . $this->record($this->driver)->getLink('journaltitle', str_replace(['{{{{START_HILITE}}}}', '{{{{END_HILITE}}}}'], '', $journalTitle)) . '">' . $this->highlight($journalTitle) . '</a>';?>
                <?=!empty($summDate) ? ' (' . $this->escapeHtml($summDate[0]) . ')' : ''?>
              </div>
              <!-- @Scheel - end -->
            <?php elseif (!empty($summDate)): ?>
              <!-- @Scheel - old code
              <?=!empty($summAuthor) ? '<br/>' : ''?>
              <?=$this->transEsc('Published') . ' ' . $this->escapeHtml($summDate[0])?>
              -->
              <!-- @Scheel - new code -->
              <div class="res-left"><?=$this->transEsc('Published')?></div>
				      <div class="res-right"><?=$this->escapeHtml($summDate[0])?></div>	
              <!-- @Scheel - end -->
            <?php endif; ?>
            <?php $summInCollection = $this->driver->getContainingCollections(); if (false && !empty($summInCollection)): ?>
              <?php foreach ($summInCollection as $collId => $collText): ?>
                <div>
                  <!-- @Scheel - old code
                  <b><?=$this->transEsc("in_collection_label")?></b>
                  <a class="collectionLinkText" href="<?=$this->url('collection', ['id' => $collId])?>?recordID=<?=urlencode($this->driver->getUniqueID())?>">
                  <?=$this->escapeHtml($collText)?>
                  </a>
                  -->
                  <!-- @Scheel - new code -->
                  <div class="res-left"><?=$this->transEsc("in_collection_label")?></b></div>
                  <div class="res-right">
                    <a class="collectionLinkText" href="<?=$this->url('collection', array('id' => $collId))?>?recordID=<?=urlencode($this->driver->getUniqueID())?>">
                    <?=$this->escapeHtml($collText)?>
                    </a>
                  </div>
                  <!-- @Scheel - end -->

                </div>
              <?php endforeach; ?>
            <?php endif; ?>
          <?php endif; ?>
        </div>

        <div class="last">
          <?php if(!$this->driver->isCollection()) {
              if ($snippet = $this->driver->getHighlightedSnippet()) {
                if (!empty($snippet['caption'])) {
                  echo '<strong>' . $this->transEsc($snippet['caption']) . ':</strong> ';
                }
                if (!empty($snippet['snippet'])) {
                  echo '<span class="quotestart">&#8220;</span>...' . $this->highlight($snippet['snippet']) . '...<span class="quoteend">&#8221;</span><br/>';
                }
              }
            } ?>

          <?php $listTags = ($this->usertags()->getMode() !== 'disabled') ? $this->driver->getTags(
              null === $list_id ? true : $list_id, // get tags for all lists if no single list is selected
              $user_id, 'tag'
             ) : [];
          ?>
          <?php if (count($listTags) > 0): ?>
              <!-- @Scheel - old code
              <strong><?=$this->transEsc('Your Tags')?>:</strong>
              <?php foreach ($listTags as $tag): ?>
                <a href="<?=$this->currentPath() . $results->getUrlQuery()->addFacet('tags', $tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a>
              <?php endforeach; ?>
              <br/>
              -->
              <!-- @Scheel - new code -->
              <div class="res-left"><?=$this->transEsc('Your Tags')?>:</div>
      			  <div class="res-right">
              <?php foreach ($listTags as $tag): ?>
              <a href="<?=$this->currentPath() . $results->getUrlQuery()->addFacet('tags', $tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a>
              <?php endforeach; ?>
              </div>
              <!-- @Scheel - end -->
          <?php endif; ?>
          <?php $listNotes = $this->driver->getListNotes($list_id, $user_id); ?>
          <?php if (count($listNotes) > 0): ?>
              <!-- @Scheel - old code
            <strong><?=$this->transEsc('Notes')?>:</strong>
            <?php if (count($listNotes) > 1): ?><br/><?php endif; ?>
            <?php foreach ($listNotes as $note): ?>
              <?=$this->escapeHtml($note)?><br/>
            <?php endforeach; ?>
              -->
              <!-- @Scheel - new code -->
              <div class="res-left"><?=$this->transEsc('Notes')?>:</div>
			   <div class="res-right">
				  <?php if (count($listNotes) > 1): ?><br/><?php endif; ?>
				  <?php foreach ($listNotes as $note): ?>
					<?=$this->escapeHtml($note)?><br/>
				  <?php endforeach; ?>
			  </div>
              <!-- @Scheel - end -->


          <?php endif; ?>

          <?php if (count($this->lists ?? []) > 0): ?>
              <!-- @Scheel - old code
              <strong><?=$this->transEsc('Saved in')?>:</strong>
              <?php $i = 0;foreach($this->lists as $current): ?>
                  <a href="<?=$this->url('userList', ['id' => $current->id])?>"><?=$this->escapeHtml($current->title)?></a><?php if($i++ < count($this->lists) - 1): ?>,<?php endif; ?>
              <?php endforeach; ?>
              <br/>
              -->
              <!-- @Scheel - new code -->
              <div class="res-left"><?=$this->transEsc('Saved in')?>:</div>
				<div class="res-right">
					<?php $i=0;foreach($this->lists as $current): ?>
						<a href="<?=$this->url('userList', array('id' => $current->id))?>"><?=$this->escapeHtml($current->title)?></a><?php if($i++ < count($this->lists)-1): ?>,<?php endif; ?>
					<?php endforeach; ?>
                </div>
              <!-- @Scheel - end -->

          <?php endif; ?>

          <!-- @Scheel - old code
          <div class="callnumAndLocation ajax-availability hidden">
          <?php if ($this->driver->supportsAjaxStatus()): ?>
              <strong class="hideIfDetailed"><?=$this->transEsc('Call Number')?>:</strong>
              <span class="callnumber ajax-availability hidden">
                <?=$this->transEsc('Loading')?>...<br/>
              </span>
              <strong><?=$this->transEsc('Located')?>:</strong>
              <span class="location ajax-availability hidden">
                <?=$this->transEsc('Loading')?>...
              </span>
              <div class="locationDetails"></div>
            <?php else: ?>
              <?php $summCallNo = $this->driver->getCallNumber(); if (!empty($summCallNo)): ?>
                <strong><?=$this->transEsc('Call Number')?>:</strong> <?=$this->escapeHtml($summCallNo)?>
              <?php endif; ?>
            <?php endif; ?>
          </div>
          -->
          <!-- @Scheel - new code -->
          <div class="callnumAndLocation ajax-availability hidden">
            <?php  if ($this->driver->supportsAjaxStatus()): ?>
              <div class="hideIfDetailed res-left"><?=$this->transEsc('Call Number')?></div>
              <div class="callnumber ajax-availability hidden res-right">
                <?=$this->transEsc('Loading')?>...
              </div>
              <div class="res-left"><?=$this->transEsc('Located')?></div>
          <div class="res-right">
                <span class="location ajax-availability hidden">
                  <?=$this->transEsc('Loading')?>...
                </span>
                <div class="locationDetails"></div>
          
          <?php if (!$openUrlActive && empty($urls) && $this->driver->supportsAjaxStatus()): ?>
            <div class="status ajax-availability hidden"><?=$this->transEsc('Loading')?>...</div>
          <?php endif; ?>
          </div>
            <?php else: ?>
              <?php $summCallNo = $this->driver->getCallNumber(); if (!empty($summCallNo)): ?>
                <div class="res-left"><?=$this->transEsc('Call Number')?></div><div class="res-right"> <?=$this->escapeHtml($summCallNo)?></div>
              <?php endif; ?>
            <?php endif; ?>
          </div>
        
          <?/*scheel: fallback location: copy getMarcHoldings here*/?>
          <!-- @Scheel - end -->

          <?php /* We need to find out if we're supposed to display an OpenURL link ($openUrlActive),
                but even if we don't plan to display the link, we still want to get the $openUrl
                value for use in generating a COinS (Z3988) tag -- see bottom of file.
              */
            $openUrl = $this->openUrl($this->driver, 'results');
            $openUrlActive = $openUrl->isActive();
            $doi = $this->doi($this->driver, 'results');
            $doiActive = $doi->isActive();
            // Account for replace_other_urls setting
            $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);

            if ($openUrlActive || $doiActive || !empty($urls)):
          ?>
            <?php if ($openUrlActive): ?>
              <br/>
              <?=$openUrl->renderTemplate()?>
            <?php endif;?>
            <!-- @Scheel - new code -->
            <?php if (!is_array($urls)) $urls = array();
              if(!$this->driver->isCollection()):?>
                <div class="res-left"><?=$this->transEsc('online_resources')?></div>
                <div class="res-right">
                  <?foreach ($urls as $current): ?>
                  <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>" class="fulltext" target="new"><i class="fa fa-external-link" aria-hidden="true"></i> <?=($current['url'] == $current['desc']) ? $this->transEsc('Get full text') : $this->escapeHtml($current['desc'])?></a><br/>
                  <?php endforeach; ?>
                </div>
              <?php endif; ?>
            <?php endif; ?>
            <!-- @Scheel - end -->

            <?php if ($doiActive): ?>
              <br/>
              <?=$doi->renderTemplate()?>
            <?php endif; ?>

            <?php if (!is_array($urls)) { $urls = []; }
              if(!$this->driver->isCollection()):
                foreach ($urls as $current): ?>
                  <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>" class="fulltext" target="new"><i class="fa fa-external-link" aria-hidden="true"></i> <?=($current['url'] == $current['desc']) ? $this->transEsc('Get full text') : $this->escapeHtml($current['desc'])?></a>
                <?php endforeach; ?>
              <?php endif; ?>
            <?php endif; ?>
          <br/>

          <?=$this->record($this->driver)->getFormatList() ?>

          <!-- @Scheel - old code
          <?php if (!$openUrlActive && empty($urls) && $this->driver->supportsAjaxStatus()): ?>
            <span class="status ajax-availability hidden"><?=$this->transEsc('Loading')?>...</span>
            <br/><br/>
          <?php endif; ?>
          -->
          <?=$this->record($this->driver)->getPreviews()?>
        </div>
      </div>

      <!-- @Scheel - old code
      <div class="result-links hidden-print">
        <i class="fa fa-fw fa-edit" aria-hidden="true"></i> <a href="<?=$this->url('myresearch-edit')?>?id=<?=urlencode($id)?>&amp;source=<?=urlencode($source)?><?php if (null !== $list_id):?>&amp;list_id=<?=urlencode($list_id)?><?php endif; ?>" class="edit tool"><?=$this->transEsc('Edit')?></a><br/>
        <?php /* Use a different delete URL if we're removing from a specific list or the overall favorites: */
          $deleteUrl = null === $list_id
              ? $this->url('myresearch-favorites')
              : $this->url('userList', ['id' => $list_id]);
          $deleteUrlGet = $deleteUrl . '?delete=' . urlencode($id) . '&amp;source=' . urlencode($source);

          $dLabel = 'delete-label-' . preg_replace('[\W]', '-', $id);
        ?>
        <div class="dropdown">
          <i class="fa fa-fw fa-trash-o" aria-hidden="true"></i> <a class="dropdown-toggle" id="<?=$dLabel ?>" role="button" data-toggle="dropdown" href="<?=$deleteUrlGet ?>">
            <?=$this->transEsc('Delete') ?>
          </a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="<?=$dLabel ?>">
            <li><a id="confirm_delete_item_<?=$this->escapeHtmlAttr($id);?>" title="<?=$this->transEsc('confirm_delete_brief')?>"><?=$this->transEsc('confirm_dialog_yes')?></a></li>
            <li><a><?=$this->transEsc('confirm_dialog_no')?></a></li>
          </ul>
        </div>

        <?=$this->driver->supportsCoinsOpenUrl()?'<span class="Z3988" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenUrl()) . '"></span>':''?>
      </div>
    </div>
    -->
    <!-- @Scheel - new code -->
      <div class="media-right" style="z-index: 2;">
        <a href="<?=$this->url('myresearch-edit')?>?id=<?=urlencode($id)?>&amp;source=<?=urlencode($source)?><?php if (!is_null($list_id)):?>&amp;list_id=<?=urlencode($list_id)?><?php endif; ?>" data-lightbox class="edit tool" title="<?=$this->transEsc('Edit')?>"><i class="fa-edit"></i></a><br/>
        <?php /* Use a different delete URL if we're removing from a specific list or the overall favorites: */
          $deleteUrl = null === $list_id
              ? $this->url('myresearch-favorites')
              : $this->url('userList', array('id' => $list_id));
          $deleteUrlGet = $deleteUrl . '?delete=' . urlencode($id) . '&amp;source=' . urlencode($source);
          $dLabel = 'delete-label-' . preg_replace('[\W]','-',$id);
        ?>
        <div class="dropdown">
          <a class="dropdown-toggle" id="<?=$dLabel ?>" role="button" data-toggle="dropdown" data-target="#" href="<?=$deleteUrlGet ?>" title="<?=$this->transEsc('Delete') ?>"><i class="fa-trash-o"></i>
          </a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="<?=$dLabel ?>">
            <li><a onClick="$.post('<?=$deleteUrl?>', {'delete':'<?=$this->escapeJs($id) ?>','source':'<?=$this->escapeJs($source) ?>','confirm':true},function(){location.reload(true)})" title="<?=$this->transEsc('confirm_delete_brief')?>"><?=$this->transEsc('confirm_dialog_yes')?></a></li>
            <li><a><?=$this->transEsc('confirm_dialog_no')?></a></li>
          </ul>
        </div>

        <?=$this->driver->supportsCoinsOpenUrl()?'<span class="Z3988" title="'.$this->escapeHtmlAttr($this->driver->getCoinsOpenUrl()).'"></span>':''?>
      </div>
    </div>
    <!-- @Scheel - end -->

    <?php if ($thumbnail && $thumbnailAlignment == 'right'): ?>
      <?=$thumbnail ?>
    <?php endif; ?>
  </div>
    
  <!-- @Scheel - new code -->
  <?php $id = $this->driver->getUniqueID() ?>
<?php $orgid = $this->driver->getOriginalID() ?>

 <div class="res-fill">
		<?=str_replace('class="', 'class="label label-info ', $this->record($this->driver)->getFormatList())?>
		<!-- scheel -->
		<?$cat = $this->driver->getCatalogue()?>
		<!-- scheel : quickfix (will be done in middleware)-->
		<?php if ($cat === 'EDISCO'):?>
			<?$catlink = 'http://www.edisco.unito.it/cgi-bin/koha/opac-detail.pl?biblionumber='.$this->escapeHtmlAttr($orgid)?>
		<?php endif;?>
		<?php if ($cat === 'MANES'):?>
			<?$catlink = 'http://www.centromanes.org:8080/cgi-bin/koha/opac-detail.pl?biblionumber='.$this->escapeHtmlAttr($orgid)?>
		<?php endif;?>
		<?php if ($cat === 'GEI'):?>
			<?$catlink = 'https://opac.lbs-braunschweig.gbv.de/DB=6.3/XMLPRS=N/PPN?PPN='.$this->escapeHtmlAttr($orgid)?>
		<?php endif;?>
		<a class='label label-cat' href='<?=$catlink?>'><?=$cat?></a>

 </div>
 
 <?php $localclassification = $this->driver->getLocalClassification();
	$notes = $this->driver->getNotes();
 if (!empty($localclassification) || !empty($notes)): ?>
 <div >
  <?php $moreClass = 'narrowGroupHidden-'.$this->escapeHtmlAttr($id).' hidden'; ?>
  <a class="" id="more-narrowGroupHidden-<?=$this->escapeHtmlAttr($id)?>" href="#" onclick="moreFacets('narrowGroupHidden-<?=$id ?>'); return false;" title="<?=$this->transEsc('more')?> ...">
	<i class="fa-fw arrow-down"></i>
  </a>
  <div class="<?=$moreClass ?> res-more">
	  <hr />
	   <?php $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
          <div class="res-left"><?=$this->transEsc('Language')?></div>
		  <div class="res-right">
				  <?php $langCount = count($langs); foreach ($langs as $i => $lang): ?>
					<?= $this->escapeHtml($this->transEsc($lang))?><?=$i + 1 < $langCount ? ',' : ''?>
				  <?php endforeach; ?>
		  </div>
      <?php endif; ?>
	  <?php  if (!empty($localclassification)): ?>
        <!--div class="res-left" ><?=$this->transEsc('textbook_classification')?></div-->
		<strong><?=$this->transEsc('textbook_classification')?></strong>
        <div class="">
          <?php foreach ($localclassification as $subfield => $field): ?>
		  <div class="subjectLine" property="keywords">
		    <?=trim($this->escapeHtml($this->transEsc($subfield)))?>:
			<?php if(is_array($field) && count($field) == 1) $field = $field[0]; ?>
			<?php foreach ($field as $f): ?>
			  <?php if (count($field) > 1): ?></br>&nbsp&nbsp&nbsp<?php endif; ?>
			  <?
			    /*scheel*/
				$subject = $f;
				if(substr( $subject, -1 ) == '/'){ //ends with slash (-> is hierarchical -> reduce to the last part)
					$subject = substr($subject, 0, strlen($subject)-1);	
					if(strripos( $subject, '/' ) > -1){
						$subject = substr($subject, strripos( $subject, '/' )+1);
					}
				}
			  ?>
			  <a title="<?=trim($this->escapeHtml($this->transEsc($subject)))?>" href="<?=$this->record($this->driver)->getLink('filter', [$subfield,$f])?>" rel="nofollow"><?=trim($this->escapeHtml($this->transEsc($subject)))?></a>
			<?php endforeach; ?>
		  </div>
          <?php endforeach; ?>
        </div>
      <?php endif; ?>
	  
	  
	  <?php  if (!empty($notes)): ?>
	    <strong><?=$this->transEsc('observations')?></strong>
		 <div class="">
			<ul>
				<?php foreach ($notes as $note): ?>
					<li><?=$note ?></li>
				<?php endforeach; ?>
			</ul>
		  </div>
	  <?php endif; ?>
	  
	  <a class="" href="#" onclick="lessFacets('narrowGroupHidden-<?=$id ?>'); return false;" title="<?=$this->transEsc('less')?> ...">
		<i class="fa-fw arrow-up"></i>
	  </a>
	</div>
  </div>
  <?php endif; ?>

  <!-- @Scheel - end -->

</div>
<?php
$escId = $this->escapeJs($id);
$escSource = $this->escapeJs($source);
$script = <<<JS
$('#confirm_delete_item_${escId}').click(function(e) {
    e.preventDefault();
    $.post('${deleteUrl}', {
                'delete':'${escId}',
                'source':'${escSource}',
                'confirm':true
            },
            function(){
                location.reload()
            }
        );
});
JS;
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
