<?php if (isset($list)): ?>
  <input type="hidden" name="listID" value="<?=$this->escapeHtmlAttr($list->id)?>" />
  <input type="hidden" name="listName" value="<?=$this->escapeHtmlAttr($list->title)?>" />
<?php endif; ?>
<?php $user = $this->auth()->isLoggedIn(); ?>
<nav class="bulkActionButtons">

<!-- @Scheel - old code
  <div class="bulk-checkbox">
    <input type="checkbox" name="selectAll" class="checkbox-select-all" id="myresearchCheckAll"/>
    <label for="myresearchCheckAll"><?=$this->transEsc('select_page')?> | <?=$this->transEsc('with_selected')?>:</label>
  </div>
  <ul class="action-toolbar">
    <li><button class="toolbar-btn btn-type-email" type="submit" name="email" value="1" title="<?=$this->transEsc('email_selected')?>"><?=$this->transEsc('Email') ?></button></li>
    <?php if ((null !== $this->list && $this->list->editAllowed($user)) || null === $this->list && $user): ?>
      <li><button class="toolbar-btn btn-type-delete" id="<?=$this->idPrefix?>delete_list_items_<?=null !== $this->list ? $this->escapeHtmlAttr($this->list->id) : ''?>" type="submit" name="delete" value="1" title="<?=$this->transEsc('delete_selected')?>"><?=$this->transEsc('Delete') ?></button></li>
    <?php endif; ?>
    <?php $exportOptions = $this->export()->getActiveFormats('bulk'); if (count($exportOptions) > 0): ?>
      <li><button class="toolbar-btn btn-type-export" type="submit" name="export" value="1" title="<?=$this->transEsc('export_selected')?>"><?=$this->transEsc('Export')?></button></li>
    <?php endif; ?>
    <li><button class="toolbar-btn btn-type-print" type="submit" name="print" value="1" title="<?=$this->transEsc('print_selected')?>" data-lightbox-ignore><?=$this->transEsc('Print')?></button></li>
    <?php if ($this->cart()->isActive()): ?>
      <li><button class="toolbar-btn btn-type-add" id="<?=$this->idPrefix?>updateCart" type="submit" name="add" value="1"><?=$this->transEsc('Add to Book Bag')?></button></li>
    <?php endif; ?>
  </ul>
-->
<!-- @Scheel - new code -->
  <div style='display:none;' >
    <label>
      <?=$this->transEsc('with_selected')?>:
    </label>
    <button id="selection-email" class="toolbar-btn btn-type-email btn-primary" type="submit" name="email" value="1" title="<?=$this->transEsc('email_selected')?>"><?=$this->transEsc('Email') ?></button>
    <?php if ((null !== $this->list && $this->list->editAllowed($user)) || null === $this->list && $user): ?>
      <button class="toolbar-btn btn-type-delete btn-primary" id="<?=$this->idPrefix?>delete_list_items_<?=null !== $this->list ? $this->escapeHtmlAttr($this->list->id) : ''?>" type="submit" name="delete" value="1" title="<?=$this->transEsc('delete_selected')?>"><?=$this->transEsc('Delete') ?></button>
    <?php endif; ?>
    <?php $exportOptions = $this->export()->getActiveFormats('bulk'); if (count($exportOptions) > 0): ?>
      <button class="toolbar-btn btn-type-export btn-primary" type="submit" name="export" value="1" title="<?=$this->transEsc('export_selected')?>"><?=$this->transEsc('Export')?></button>
    <?php endif; ?>
    <button class="toolbar-btn btn-type-print btn-primary" type="submit" name="print" value="1" title="<?=$this->transEsc('print_selected')?>" ><?=$this->transEsc('Print')?></button>
    <?php if ($this->cart()->isActive()): ?>
      <button class="toolbar-btn btn-type-add btn-primary" id="<?=$this->idPrefix?>updateCart" type="submit" name="add" value="1"><?=$this->transEsc('Add to Book Bag')?></button>
    <?php endif; ?>
  </div>
  <!-- @Scheel - end -->
  <div class="bulk-checkbox">
    <label>
      <input type="checkbox" name="selectAll" class="checkbox-select-all" id="myresearchCheckAll"/>
      <!-- @Scheel - old code
      <label for="myresearchCheckAll"><?=$this->transEsc('select_page')?> | <?=$this->transEsc('with_selected')?>:</label>
      -->
      <!-- @Scheel - new code -->
      <label for="myresearchCheckAll"><?=$this->transEsc('select_page')?> :</label>
      <!-- @Scheel - end -->
    </label>
  </div>
</nav>