<?php
  // Set up page title:
  $this->headTitle($this->translate('Edit') . ' : ' . $this->driver->getBreadcrumb());
  // @Scheel - new code
  $this->layout()->editview = true;
  $this->layout()->edunav =['','','',''];
  $this->layout()->searchbox = false;
  // @Scheel - end

  // Set up breadcrumbs:
  /* @Scheel - old code
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Edit') . '</li>';
  */
?>
<div class="record">
  <!-- @Scheel - old code
  <h2><?=$this->escapeHtml($this->driver->getBreadcrumb())?></h2>
  -->
  <!-- @Scheel - new code -->
  <h2 class="row edu-link"><?=$this->escapeHtml($this->driver->getBreadcrumb())?></h2>
  <!-- @Scheel - end -->
  <form class="form-list-edit" method="post" name="editForm">
  <?php if (empty($this->savedData)): ?>
    <p class="alert alert-info">
      <?php if (isset($listFilter)): ?>
        <?=$this->transEsc('The record you selected is not part of the selected list.') ?>
      <?php else: ?>
        <?=$this->transEsc('The record you selected is not part of any of your lists.') ?>
      <?php endif; ?>
    </p>
  <?php else: ?>
    <div class="list-edit-container">
      <?php foreach ($this->savedData as $i => $current): ?>
        <!-- @Scheel - new code -->
        <div class="group">
          <div class="form-group">
            <label class="col-sm-1 control-label"><?=$this->transEsc('List').':'?></label>
            <div class="col-sm-10">
              <h3><?=$this->transEsc('List') ?>: <?=$this->escapeHtml($current['listTitle'])?></h3>
            </div>
          </div>
        <!-- @Scheel - end -->
        <!-- @Scheel - old code
        <fieldset class="list-edit-group">
          <h3><?=$this->transEsc('List') ?>: <?=$this->escapeHtml($current['listTitle'])?></h3>
          -->
          <input type="hidden" name="lists[]" value="<?=$current['listId'] ?>"/>
          <?php if ($this->usertags()->getMode() !== 'disabled'): ?>
            <div class="form-group">
              <label class="control-label" for="edit_tags<?=$current['listId'] ?>"><?=$this->transEsc('Tags') ?>:</label>
              <input type="text" name="tags<?=$current['listId'] ?>" id="edit_tags<?=$current['listId'] ?>" class="form-control" value="<?=$this->escapeHtmlAttr($current['tags'])?>"/>
              <span class="help-block"><?=$this->transEsc("add_tag_note") ?></span>
            </div>
          <?php endif; ?>
          <div class="form-group">
            <label class="control-label" for="edit_notes<?=$current['listId'] ?>"><?=$this->transEsc('Notes') ?>:</label>
            <textarea class="form-control" id="edit_notes<?=$current['listId'] ?>" name="notes<?=$current['listId'] ?>" rows="3"><?=$this->escapeHtml($current['notes'])?></textarea>
          </div>
          <a href="<?=$this->url('userList', ['id' => $current['listId']]) ?>?delete=<?=urlencode($this->driver->getUniqueId())?>&amp;source=<?=urlencode($this->driver->getSourceIdentifier())?>" id="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>delete<?=$current['listId'] ?>" data-lightbox>
            <i class="fa fa-trash"></i> <?=$this->transEsc('Delete') ?>
          </a>
        <!-- @Scheel - old code
        </fieldset>
        -->
        <!-- @Scheel - new code -->
        </div>
        <!-- @Scheel - end-->
      <?php endforeach; ?>
    </div>
  <?php endif; ?>
  <?php if (count($this->lists) > 0): ?>
    <hr/>
    <div class="form-group">
      <select name="addToList" class="form-control">
        <option value="-1">- <?=$this->transEsc('Add to another list')?> -</option>
        <?php foreach ($this->lists as $listID => $listTitle): ?>
          <option value="<?=$listID ?>"><?=$this->escapeHtml($listTitle) ?></option>
        <?php endforeach; ?>
      </select>
    </div>
  <?php endif; ?>
  <?php if (!empty($this->savedData) || count($this->lists) > 0): ?>
    <div class="form-group">
      <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Save') ?>"/>
    </div>
  <?php endif; ?>
  </form>
</div>
