<?php
  $user = $this->auth()->isLoggedIn();
  $patron = $user ? $this->auth()->getILSPatron() : false;
  $capabilityParams = $patron ? ['patron' => $patron] : [];
  $ilsOnline = ('ils-none' !== $this->ils()->getOfflineMode());
?>
<button class="close-offcanvas btn btn-link" data-toggle="offcanvas"><?=$this->transEsc('navigate_back') ?></button>

<!-- @Scheel - old code
<h3><?=$this->transEsc('Your Account')?></h3>
-->
<!-- @SajadKarim - Previos names for div were list-group (myresearch-menu) and list-group-item (see old archive). TODO:  I added "-item" considering just names has been change but need to confirm if such css-class exists or not!-->
<!-- @SajadKarim - Div's names are different in newer version therefore moving content as per the hierarchy of the elements/tags-->
<!-- @Scheel - new code -->
<?php if (isset($this->layout()->mylist)): ?>
  <div class="myresearch-menu filters">
  <div class="myresearch-menu-item title"><?=$this->transEsc('with_selected')?></div>
  <a href="javascript:void(0)" onclick="document.getElementsByName('email')[0].click();" class="myresearch-menu-item">
  <?=$this->transEsc('Email') ?>
  <span class="pull-right flip"><i class="fa fa-fw fa-envelope"></i></span>
  </a>
  <a href="javascript:void(0)" onclick="document.getElementsByName('delete')[0].click();" class="myresearch-menu-item">
  <?=$this->transEsc('Delete') ?>
  <span class="pull-right flip"><i class="fa fa-fw fa-trash-o"></i></span>
  </a>
  <a href="javascript:void(0)" onclick="document.getElementsByName('export')[0].click();" class="myresearch-menu-item">
  <?=$this->transEsc('export_selected') ?>
  <span class="pull-right flip"><i class="fa fa-fw fa-list-alt"></i></span>
  </a>
  <a href="javascript:void(0)" onclick="document.getElementsByName('print')[0].click();" class="myresearch-menu-item">
  <?=$this->transEsc('print_selected') ?>
  <span class="pull-right flip"><i class="fa fa-fw fa-print"></i></span>
  </a>
  </div>
<? endif; ?>
<!-- @Scheel - end -->
<!-- @SajadKarim - Previos names for div were list-group (myresearch-menu) and list-group-item (see old archive). TODO:  I added "-item" considering just names has been change but need to confirm if such css-class exists or not!-->
<!-- @Scheel - new code -->
<div class="myresearch-menu account-menu filters">
  <div class="myresearch-menu-item title"><?=$this->transEsc('Your Account')?></div>
<!-- @Scheel - end -->
<div class="myresearch-menu account-menu">
  <!-- @Scheel - old code
  <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
    <a href="<?=$this->url('myresearch-favorites')?>"<?=$this->active == 'favorites' ? ' class="active"' : ''?>>
      <i class="fa fa-fw fa-star" aria-hidden="true"></i> <?=$this->transEsc('Favorites')?>
    </a>
  <?php endif; ?>
  -->
  <?php if ($ilsOnline && $this->ils()->checkCapability('getMyTransactions', $capabilityParams)): ?>
    <a href="<?=$this->url('myresearch-checkedout')?>" class="flex checkedout<?=$this->active == 'checkedout' ? ' active' : ''?>">
      <span class="flex-col"><i class="fa fa-fw fa-book" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('Checked Out Items')?></span>
      <span class="checkedout-status status hidden"><i class="fa fa-spin fa-spinner" aria-hidden="true"></i></span>
    </a>
  <?php endif; ?>
  <?php if ($ilsOnline && $this->ils()->checkFunction('getMyTransactionHistory', $capabilityParams)): ?>
    <a href="<?=$this->url('myresearch-historicloans')?>"<?=$this->active == 'historicloans' ? ' class="active"' : ''?>>
      <i class="fa fa-fw fa-history" aria-hidden="true"></i> <?=$this->transEsc('Loan History')?>
    </a>
  <?php endif; ?>
  <?php if ($ilsOnline && $this->ils()->checkCapability('getMyHolds', $capabilityParams)): ?>
    <a href="<?=$this->url('myresearch-holds')?>" class="flex<?=$this->active == 'holds' ? ' active' : ''?>">
      <span class="flex-col"><i class="fa fa-fw fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('Holds and Recalls')?></span>
      <span class="holds-status status hidden"><i class="fa fa-spin fa-spinner" aria-hidden="true"></i></span>
    </a>
  <?php endif; ?>
  <?php if ($ilsOnline && $this->ils()->checkFunction('StorageRetrievalRequests', $capabilityParams)): ?>
    <a href="<?=$this->url('myresearch-storageretrievalrequests')?>" class="flex<?=$this->active == 'storageRetrievalRequests' ? ' active' : ''?>">
      <span class="flex-col"><i class="fa fa-fw fa-archive" aria-hidden="true"></i> <?=$this->transEsc('Storage Retrieval Requests')?></span>
      <span class="storageretrievalrequests-status status hidden"><i class="fa fa-spin fa-spinner" aria-hidden="true"></i></span>
    </a>
  <?php endif; ?>
  <?php if ($ilsOnline && $this->ils()->checkFunction('ILLRequests', $capabilityParams)): ?>
    <a href="<?=$this->url('myresearch-illrequests')?>" class="flex<?=$this->active == 'ILLRequests' ? ' active' : ''?>">
      <span class="flex-col"><i class="fa fa-fw fa-exchange" aria-hidden="true"></i> <?=$this->transEsc('Interlibrary Loan Requests')?></span>
      <span class="illrequests-status status hidden"><i class="fa fa-spin fa-spinner" aria-hidden="true"></i></span>
    </a>
  <?php endif; ?>
  <?php if ($ilsOnline && $this->ils()->checkCapability('getMyFines', $capabilityParams)): ?>
    <a href="<?=$this->url('myresearch-fines')?>" class="flex<?=$this->active == 'fines' ? ' active' : ''?>">
      <span class="flex-col"><i class="fa fa-fw fa-usd" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('Fines')?></span>
      <span class="fines-status status hidden"><i class="fa fa-spin fa-spinner" aria-hidden="true"></i></span>
    </a>
  <?php endif; ?>
  <a href="<?=$this->url('myresearch-profile')?>"<?=$this->active == 'profile' ? ' class="active"' : ''?>>
    <i class="fa fa-fw fa-user" aria-hidden="true"></i> <?=$this->transEsc('Profile')?>
  </a>
  <?php if ($ilsOnline && $user && $user->libraryCardsEnabled()): ?>
    <a href="<?=$this->url('librarycards-home')?>"<?=$this->active == 'librarycards' ? ' class="active"' : ''?>>
      <i class="fa fa-fw fa-barcode" aria-hidden="true"></i> <?=$this->transEsc('Library Cards')?>
    </a>
  <?php endif; ?>
  <?php if ($this->overdrive()->showMyContentLink()):?>
     <a href="<?=$this->url('overdrive-mycontent')?>"<?=$this->active == 'dgcontent' ? ' class="active"' : ''?>>
      <i class="fa fa-fw fa-download" aria-hidden="true"></i> <?=$this->transEsc('Overdrive Content')?>
    </a>
  <?php endif; ?>
  <!-- @Scheel - old code
  <?php if ($this->accountCapabilities()->getSavedSearchSetting() === 'enabled'): ?>
    <a href="<?=$this->url('search-history')?>?require_login"<?=$this->active == 'history' ? ' class="active"' : ''?>>
      <i class="fa fa-fw fa-search" aria-hidden="true"></i> <?=$this->transEsc('history_saved_searches')?>
    </a>
  <?php endif; ?>
  -->
  <?php if ($user): ?>
    <a href="<?=$this->url('myresearch-logout')?>">
      <i class="fa fa-fw fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?>
    </a>
  <?php endif; ?>
</div>

<?php if ($user && $this->userlist()->getMode() !== 'disabled'): ?>
  <!-- @Scheel - old code
  <h3><?=$this->transEsc('Your Lists')?></h3>
  <div class="myresearch-menu">
  -->
  <!-- @Scheel - new code -->
    <!-- @SajadKarim - Previos names for div were list-group (myresearch-menu) and list-group-item (see old archive). TODO:  I added "-item" considering just names has been change but need to confirm if such css-class exists or not!-->
    <div class="myresearch-menu filters">
  	  <div class="myresearch-menu-item title"><?=$this->transEsc('Your Lists')?></div>
  <!-- @Scheel - end -->
    <a href="<?=$this->url('myresearch-favorites')?>"<?=$this->active == 'favorites' ? ' class="active"' : ''?>>
      <i class="fa fa-fw fa-star" aria-hidden="true"></i> <?=$this->transEsc('Your Favorites')?>
    </a>
    <?php $lists = $user->getLists() ?>
    <?php foreach ($lists as $list): ?>
      <a href="<?=$this->url('userList', ['id' => $list['id']])?>"<?=$this->active == 'list' . $list['id'] ? ' class="active"' : ''?>>
        <?=$this->escapeHtml($list['title'])?>
        <span class="badge"><?=$list->cnt ?></span>
      </a>
    <?php endforeach; ?>
    <a href="<?=$this->url('editList', ['id' => 'NEW'])?>">
      <i class="fa fa-fw fa-plus" aria-hidden="true"></i> <?=$this->transEsc('Create a List') ?>
    </a>
  </div>
<?php endif ?>
