<? include 'themes/gei/templates/gei/gei-result-data.php' ?>

<?
// Set up some convenience variables:
$id = $this->driver->getUniqueId();
$source = $this->driver->getSourceIdentifier();
if (isset($this->list) && is_object($this->list)) {
  $list_id = $this->list->id;
  $user_id = $this->list->user_id;
} else {
  $list_id = null;
  $user_id = $this->user ? $this->user->id : null;
}
?>

<div class="result">
  <article class="gei-result theme-<?=$portalId ?>">

    <!-- BEGIN: TCard Header -->
    <div class="gei-result__header">

      <input type="hidden" value="<?=$this->escapeHtmlAttr($id) ?>" class="hiddenId"/>
      <input type="hidden" value="<?=$this->escapeHtmlAttr($source) ?>" class="hiddenSource"/>

      <div class="gei-result__checkbox">
        <?=$this->record($this->driver)->getCheckbox()?>
      </div>

      <? if ($portalName): ?>
        <!-- BEGIN: Portal Name -->
        <div class="gei-result__portal">
          <?=$portalName ?>
        </div>
        <!-- END: Portal Name -->
      <? endif ?>

    </div>
    <!-- END: Card Header -->

    <!-- BEGIN: Body -->
    <div class="gei-result__body">

      <header>
        <? if (count($beforeTitle) > 0 ): ?>
          <!-- BEGIN: Meta before title -->
          <div class="gei-result__kicker">
            <?=$this->highlight(implode(', ', $beforeTitle))?>
          </div>
          <!-- END: Meta before title -->
        <? endif ?>

        <!-- BEGIN: Title -->
        <h3 class="gei-result__title">
          <a href="<?=$this->recordLink()->getUrl($this->driver)?>" data-view="<?=$this->params->getOptions()->getListViewOption() ?>">
            <?=$title ?>
          </a>
        </h3>
        <!-- END: Title -->

        <? if (count($afterTitle) > 0 ): ?>
          <!-- BEGIN: Meta after title -->
          <div class="gei-result__meta">
            <?=$this->highlight(implode(' ', $afterTitle))?>
          </div>
          <!-- END: Meta after title -->
        <? endif ?>
      </header>

      <!-- BEGIN: Content -->
      <div class="gei-result__content">

        <? if ($cover): ?>
          <!-- BEGIN: Image -->
          <figure class="gei-result__image">
            <?=$cover ?>
          </figure>
          <!-- END: Image -->
        <? endif ?>

        <div class="gei-result__data-panel">
          <? if((count($dataTable) > 0 )): ?>
            <!-- BEGIN: Data-Table -->
            <table class="gei-result__data">
              <?
              foreach ($dataTable as $key => $value) {
                echo '<tr><th>' . $key . '</th><td>' . $value . '</td></tr>';
              }
              ?>
            </table>
            <!-- END: Data-Table -->
          <? endif; ?>

          <? if(!$this->driver->isCollection() & $snippet): ?>
            <!-- BEGIN: Excerpt -->
            <div class="gei-result__snippet">
              <? if (!empty($snippet['caption'])): ?>
                <span class="visuallyhidden"><?=$this->transEsc($snippet['caption']) ?>:</span>
              <? endif; ?>
              <? if (!empty($snippet['snippet'])): ?>
                <?=$this->highlight($snippet['snippet']) ?>...
              <? elseif (!empty($snippet['teaser'])): ?>
                <?=$this->highlight($snippet['teaser']) ?>...
              <? endif; ?>
            </div>
            <!-- END: Excerpt -->
          <? endif; ?>
        </div>

      </div>
      <!-- END: Content -->

      <?
      /* Display information on duplicate records if available */
      if ($dedupData = $this->driver->getDedupData()): ?>
      <div class="dedupInformation">
        <?
        $i = 0;
        foreach ($dedupData as $source => $current) {
          if (++$i == 1) {
            ?><span class="currentSource"><a href="<?=$this->recordLink()->getUrl($this->driver)?>"><?=$this->transEsc("source_$source", array(), $source)?></a></span><?
          } else {
            if ($i == 2) {
              ?> <span class="otherSources">(<?=$this->transEsc('Other Sources')?>: <?
            } else {
              ?>, <?
            }
            ?><a href="<?=$this->recordLink()->getUrl($current['id'])?>"><?=$this->transEsc("source_$source", array(), $source)?></a><?
          }
        }
        if ($i > 1) {
          ?>)</span><?
        }?>
      </div>
    <? endif; ?>

    <div class="callnumAndLocation ajax-availability hidden">
      <? if ($this->driver->supportsAjaxStatus()): ?>
        <strong class="hideIfDetailed"><?=$this->transEsc('Call Number')?>:</strong>
        <span class="callnumber ajax-availability hidden">
          <?=$this->transEsc('Loading')?>...<br/>
        </span>
        <strong><?=$this->transEsc('Located')?>:</strong>
        <span class="location ajax-availability hidden">
          <?=$this->transEsc('Loading')?>...
        </span>
        <div class="locationDetails"></div>
      <? else: ?>
        <? $summCallNo = $this->driver->getCallNumber(); if (!empty($summCallNo)): ?>
        <strong><?=$this->transEsc('Call Number')?>:</strong> <?=$this->escapeHtml($summCallNo)?>
      <? endif; ?>
    <? endif; ?>
  </div>

  <?
  $openUrl = $this->openUrl($this->driver, 'results');
  $openUrlActive = $openUrl->isActive();
      // Account for replace_other_urls setting
  $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);

  if ($openUrlActive || !empty($urls)): ?>
  <? if ($openUrlActive): ?>
    <br/>
    <?=$openUrl->renderTemplate()?>
  <? endif; ?>
  <? if (!is_array($urls)) $urls = array();
  if(!$this->driver->isCollection()): ?>
  <div class="gei-result__links">
    <? foreach ($urls as $current): ?>
      <span><a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>" class="fulltext" target="new"><?=($current['url'] == $current['desc']) ? $this->transEsc('Link') : $this->escapeHtml($current['desc'])?></a></span>
    <? endforeach; ?>
  </div>
<? endif; ?>
<? endif; ?>

<? if (!$openUrlActive && empty($urls) && $this->driver->supportsAjaxStatus()): ?>
  <span class="status ajax-availability hidden">
    <span class="label label-default"><?=$this->transEsc('Loading')?>...</span>
  </span>
<? endif; ?>
<?=$this->record($this->driver)->getPreviews()?>


</div>
<!-- END: Body -->

<!-- BEGIN: Footer -->
<footer class="gei-result__footer">
  <!-- BEGIN: Actions -->
  <div class="gei-result__actions hidden-print">

    <div class="gei-result__action gei-result__action--edit">
      <i class="fa fa-fw fa-edit" aria-hidden="true"></i> <a href="<?=$this->url('myresearch-edit')?>?id=<?=urlencode($id)?>&amp;source=<?=urlencode($source)?><? if (!is_null($list_id)):?>&amp;list_id=<?=urlencode($list_id)?><? endif; ?>" class="edit tool"><?=$this->transEsc('Edit')?></a>
    </div>
    <div class="gei-result__action gei-result__action--delete">
      <? /* Use a different delete URL if we're removing from a specific list or the overall favorites: */
      $deleteUrl = null === $list_id
      ? $this->url('myresearch-favorites')
      : $this->url('userList', array('id' => $list_id));
      $deleteUrlGet = $deleteUrl . '?delete=' . urlencode($id) . '&amp;source=' . urlencode($source);

      $dLabel = 'delete-label-' . preg_replace('[\W]','-',$id);
      ?>
      <div class="dropdown">
        <i class="fa fa-fw fa-trash-o" aria-hidden="true"></i> <a class="dropdown-toggle" id="<?=$dLabel ?>" role="button" data-toggle="dropdown" href="<?=$deleteUrlGet ?>">
          <?=$this->transEsc('Delete') ?>
        </a>
        <ul class="dropdown-menu" role="menu" aria-labelledby="<?=$dLabel ?>">
          <li><a onClick="$.post('<?=$deleteUrl?>', {'delete':'<?=$this->escapeJs($id) ?>','source':'<?=$this->escapeJs($source) ?>','confirm':true},function(){location.reload(true)})" title="<?=$this->transEsc('confirm_delete_brief')?>"><?=$this->transEsc('confirm_dialog_yes')?></a></li>
          <li><a><?=$this->transEsc('confirm_dialog_no')?></a></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- END: Actions -->
  <?=$this->driver->supportsCoinsOpenUrl()?'<span class="Z3988" title="'.$this->escapeHtmlAttr($this->driver->getCoinsOpenUrl()).'"></span>':''?>
</footer>
<!-- END: Footer -->

</article>
</div>
