<!-- @Scheel - old code
<h2><?=$this->transEsc('Similar Items')?></h2>
-->
<!-- @Scheel - new code -->
<div class="">
<!-- @Scheel - end -->
<?php $similarRecords = $this->related->getResults(); ?>
<!-- @Scheel - old code
<?php if (!empty($similarRecords)): ?>
  <ul class="list-group">
    <?php foreach ($similarRecords as $data): ?>
      <li class="list-group-item">
-->
<!-- @Scheel - new code -->
<div class="list-group filters">
  <div class="list-group-item title"><?=$this->transEsc('Similar Items')?></div>
<?php if (!empty($similarRecords) && sizeof($similarRecords)!=0): ?>
  <?php foreach ($similarRecords as $data): ?>
      <span class="list-group-item">
<!-- @Scheel - end -->

        <?php $formats = $data->getFormats(); ?>
        <i class="fa fa-x<?php if (count($formats) > 0): ?> fa-<?=preg_replace('/[^a-z0-9]/', '', strtolower($formats[0]))?>" title="<?=$formats[0] ?><?php endif; ?>"></i>
        <a href="<?=$this->recordLink()->getUrl($data)?>">
          <?=$this->escapeHtml($data->getTitle())?>
        </a>

<!-- @Scheel - old code
<?php $authors = $data->getPrimaryAuthors(); if (!empty($authors)): ?>
          <br/><?=$this->transEsc('by')?>: <?=$this->escapeHtml($authors[0]);?><?php if (count($authors) > 1): ?>, <?=$this->transEsc('more_authors_abbrev')?><?php endif; ?>
-->
<!-- @Scheel - new code -->
<?php $author = $data->getPrimaryAuthor(); if (!empty($author)): ?>
          <br/><?=$this->transEsc('by')?>: <?=$this->escapeHtml($author);?>
<!-- @Scheel - end -->

        <?php endif; ?>
        <?php $pubDates = $data->getPublicationDates(); if (!empty($pubDates)): ?>
          <br/><?=$this->transEsc('Published')?>: (<?=$this->escapeHtml($pubDates[0])?>)
        <?php endif; ?>

<!-- @Scheel - old code
      </li>
      <?php endforeach; ?>
  </ul>
-->
<!-- @Scheel - new code -->
</span>
    <?php endforeach; ?>
<!-- @Scheel - end -->

<?php else: ?>

<!-- @Scheel - old code
  <p><?=$this->transEsc('Cannot find similar records')?></p>
<?php endif; ?>
  </ul>
-->
<!-- @Scheel - new code -->
<span class="list-group-item">
		<p><?=$this->transEsc('Cannot find similar records')?></p>
	</span>
<? endif; ?>
  </div>

</div>
<!-- @Scheel - end -->

