<?php
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $openUrl = $this->openUrl($this->driver, 'holdings');
    $openUrlActive = $openUrl->isActive();
    $doi = $this->doi($this->driver, 'holdings');
    $doiActive = $doi->isActive();
    // Account for replace_other_urls setting
    $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
    $offlineMode = $this->ils()->getOfflineMode();
    try {
        $holdings = $this->driver->getRealTimeHoldings();
    } catch (\VuFind\Exception\ILS $e) {
        $holdings = [
          'holdings' => [],
          'electronic_holdings' => [],
          'total' => 0,
          'page' => 0,
          'itemLimit' => 0
        ];
        $offlineMode = 'ils-offline';
    }
    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
?>

<?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

<?php if (!empty($holdings['blocks'])):?>
  <div id="account-block-msg" class="alert alert-danger">
    <?=$this->transEsc('account_block_options_missing', ['%%details%%' => implode('; ', $holdings['blocks'])]) ?>
  </div>
<?php endif; ?>

<?=($offlineMode == "ils-offline") ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message']) : ''?>

<?php if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings['holdings'])) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <?php if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <?php if (!$user): ?>
      <div class="alert alert-info">
        <!-- @Scheel - old code
        <a href="<?=$this->recordLink()->getTabUrl($this->driver, 'Holdings', ['login' => 'true', 'catalogLogin' => 'true'])?>" data-lightbox><?=$this->transEsc("hold_login")?></a>
        -->
        <!-- @Scheel - new code -->
        <a href="<?=$this->recordLink()->getTabUrl($this->driver, 'Holdings', ['login' => 'true', 'catalogLogin' => 'true'])?>" target="_blank"><?=$this->transEsc("hold_login")?></a>
        <!-- @Scheel - end -->
      </div>
    <?php elseif (!$user->cat_username): ?>
      <div class="alert alert-info">
        <?=$this->translate("hold_profile_html", ['%%url%%' => $this->recordLink()->getTabUrl($this->driver, 'Holdings', ['catalogLogin' => 'true'])])?>
      </div>
    <?php endif; ?>
  <?php endif; ?>
<?php endif; ?>
<?php $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
<!-- @Scheel - old code
  <a class="placehold" data-lightbox title="<?=$this->transEsc('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('title_hold_place')?></a>
-->
<!-- @Scheel - new code -->
  <a class="placehold" target="_blank" title="<?=$this->transEsc('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('title_hold_place')?></a>
<!-- @Scheel - end -->
<?php endif; ?>
<?php if (!empty($urls) || $openUrlActive || $doiActive): ?>
  <h3><?=$this->transEsc("Internet")?></h3>
  <?php if (!empty($urls)): ?>
    <?php foreach ($urls as $current): ?>
      <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
    <?php endforeach; ?>
  <?php endif; ?>
  <?php if ($openUrlActive): ?><?=$openUrl->renderTemplate()?><?php endif; ?>
  <?php if ($doiActive): ?><?=$doi->renderTemplate()?><?php endif; ?>
<?php endif; ?>

<?php if (!empty($holdings['electronic_holdings'])): ?>
  <?=$this->context($this)->renderInContext(
      'RecordTab/holdingsils/electronic.phtml',
      ['holdings' => $holdings['electronic_holdings']]
  );?>
<?php endif; ?>

<!-- @Scheel - new code -->
<!--?="<script>console.log( " . json_encode($holdings) . " );</script>" ?-->
<?php if (!empty($holdings) && is_string($holdings[0]) ): /*scheel*/?>
	<ul>
	<?php foreach ($holdings as $holding): ?>
		<li><?=$holding?></li>
	<?php endforeach; ?>
	</ul>
<?php endif; ?>
<!-- @Scheel - end -->

<?php foreach ($holdings['holdings'] ?? [] as $holding): ?>
<h3>
  <!-- @Scheel - old code
  <?php $locationText = $this->transEscWithPrefix('location_', $holding['location']); ?>
  -->
<!-- @Scheel - new code -->
  <?php $locationText = $this->transEscWithPrefix('location', $holding['location']); ?>
<!-- @Scheel - end -->
  <?php if ($holding['locationhref'] ?? false): ?>
    <a href="<?=$holding['locationhref']?>" target="_blank"><?=$locationText?></a>
  <?php else: ?>
    <?=$locationText?>
  <?php endif; ?>
</h3>

<!-- @Scheel - old code
<table class="table table-striped">
-->
<!-- @Scheel - new code -->
<table class="table edu-table table-striped">
<!-- @Scheel - end -->
  <caption class="sr-only"><?=$this->transEsc('holdings_details_from', ['%%location%%' => $this->transEsc($holding['location'])]) ?></caption>
  <?php $callNos = $this->tab->getUniqueCallNumbers($holding['items']); if (!empty($callNos)): ?>
  <tr>
    <th><?=$this->transEsc("Call Number")?>: </th>
    <td width="50%">
      <?php foreach ($callNos as $callNo): ?>
        <?php if ($this->callnumberHandler): ?>
          <a href="<?=$this->url('alphabrowse-home') ?>?source=<?=$this->escapeHtmlAttr($this->callnumberHandler) ?>&amp;from=<?=$this->escapeHtmlAttr($callNo) ?>"><?=$this->escapeHtml($callNo)?></a>
        <?php else: ?>
          <?=$this->escapeHtml($callNo)?>
        <?php endif; ?>
        <br />
      <?php endforeach; ?>
    </td>
  </tr>
  <?php endif; ?>
  <?php foreach ($holding['textfields'] ?? [] as $textFieldName => $textFields): ?>
    <tr>
      <?php // Translation for summary is a special case for backwards-compatibility ?>
      <th><?=$textFieldName == 'summary' ? $this->transEsc("Volume Holdings") : $this->transEsc(ucfirst($textFieldName))?>:</th>
      <td>
        <?php foreach ($textFields as $current): ?>
          <?=$this->linkify($this->escapeHtml($current))?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endforeach; ?>
  <?php foreach ($holding['items'] as $row): ?>
    <?php
        try {
            echo $this->context($this)->renderInContext(
                'RecordTab/holdingsils/' . $this->tab->getTemplate() . '.phtml',
                ['holding' => $row]
            );
        } catch (Exception $e) {
            echo $this->context($this)->renderInContext(
                'RecordTab/holdingsils/standard.phtml',
                ['holding' => $row]
            );
        }
    ?>
  <?php endforeach; ?>
  <?php if (!empty($holding['purchase_history'])): ?>
    <tr>
      <th><?=$this->transEsc("Most Recent Received Issues")?>:</th>
      <td>
        <?php foreach ($holding['purchase_history'] as $current): ?>
          <?=$this->escapeHtml($current['issue'])?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>
</table>
<?php endforeach; ?>
<?php if (!empty($holdings['total']) && $paginator = $this->tab->getPaginator($holdings['total'], $holdings['page'], $holdings['itemLimit'])): ?>
  <?=$this->paginationControl($paginator, 'Sliding', 'Helpers/pagination.phtml', ['page' => $holdings['page']])?>
<?php endif; ?>
<?php $history = $this->driver->getRealTimeHistory(); ?>
<?php if (is_array($history) && !empty($history)): ?>
  <h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
  <table class="table table-striped">
    <?php foreach ($history as $row): ?>
      <tr><td><?=$this->escapeHtml($row['issue'])?></td></tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>
<!-- @SajadKarim - There is some more code to move from old code but I could not find any equivalent code in newer version... so need to track the chagne from SVN -->
