<? $this->headTitle($this->translate('information')); ?>
<div class="imprint">
	<h1 class="">International TextbookCat</h1>
	
	
<h2><strong>Ziele und Zielgruppe</strong>&nbsp;</h2>

Langfristiges Ziel des International TextbookCat ist es, den SchulbuchwissenschaftlerInnen einen zentralen Sucheinstieg zu internationalen Schulbüchern innerhalb weltweit vorhandener Schulbuchsammlungen und -Datenbanken zu ermöglichen. Um dieses Vorhaben zu ermöglichen, wurde eine differenzierte Schulbuchsystematik verwendet, die Ihnen innerhalb des International TextbookCat als Sucheinstieg in Form verschiedener Facetten, wie Nutzungsland, Bildungslevel und Unterrichtsfach zur Verfügung steht. Für Schulbücher aus Deutschland ist zusätzlich eine Facettierung nach Bundesland und Schultyp möglich. Zusätzlich stehen Facetten für nicht-schulbuchspezifische Eigenschaften wie Sprache und Veröffentlichungsjahr zur Verfügung.
 <br />
Das Projekt konzentriert sich zunächst auf die Zusammenführung von Schulbuchdatenbanken von drei Institutionen - dem Georg-Eckert-Institut (GEI), der Universita degli Studi di Torino (Datenbank EDISCO) und der Universidad Nacional de Educación a Distancia (Datenbank MANES)- zu einem gemeinsamen Nachweisinstrument. Es werden Workflows und Architekturen erarbeitet, die langfristig dazu beitragen, dass weitere Institutionen mit geringem Eigenaufwand Teil des Nachweisinstruments werden können.

<h2><strong>Datensätze</strong>&nbsp;</h2>
Der International TextbookCat führt die Schulbuchdatenbanken von drei Institutionen - dem Georg-Eckert-Institut (GEI), der Universita degli Studi di Torino (Datenbank EDISCO) und der Universidad Nacional de Educación a Distancia (Datenbank MANES)- zu einem gemeinsamen Nachweisinstrument zusammen. Um nur die Bestände einer einzelnen Institution angezeigt zu bekommen, wählen Sie einen der drei vorhandenen Kataloge aus. Für die Recherche in allen Katalogen, lassen Sie diese Facette unberücksichtigt und wählen Sie den Sucheinstieg direkt über eine der weiteren Facetten.
<br />
Die dem International TextbookCat zugrunde liegende Architektur sorgt dafür, dass alle Kataloge mindestens wochenaktuell recherchiert werden können.

<h3>GEI</h3>
Die Schulbuchsammlung des Georg-Eckert-Institutes (GEI) umfasst 177.000 Print- und Online-Medien aus 173 Ländern aus der Zeit vom 17. Jahrhundert bis heute. Um den gesamten Umfang dieser Sammlung zu sehen, wählen Sie innerhalb der Facette "Schulbuchkatalog" das GEI aus.
<br />
Weiterführende Links:
<ul>
<li> <a href="https://opac.lbs-braunschweig.gbv.de/DB=6/">https://opac.lbs-braunschweig.gbv.de/DB=6/</a></li>
</ul>

<h3>EDISCO</h3>
Die Datenbank EDISCO bietet einen Nachweis über 25.000 italienische Schulbücher, die hauptsächlich im 19. und 20. Jahrhundert erschienen sind. Um den gesamten Umfang dieser Datenbank zu sehen, wählen Sie innerhalb der Facette "Schulbuchkatalog" die Datenbank EDISCO aus.
<br />
Weiterführende Links:
<ul>
<li> <a href="http://www.database-edisco.org">http://www.database-edisco.org</a></li>
</ul>

<h3>MANES</h3>
Die Datenbank MANES bietet einen Nachweis über 35.000 Schulbücher aus dem 19. und 20. Jahrhundert aus Spanien, Portugal, Lateinamerika und Belgien. Um den gesamten Umfang dieser Datenbank zu sehen, wählen Sie innerhalb der Facette "Schulbuchkatalog" die Datenbank MANES aus.
<br />
Weiterführende Links:
<ul>
<li> <a href="http://www.centromanes.org">http://www.centromanes.org</a></li>
</ul>

<h2><strong>Schulbuchspezifische Eigenschaften</strong>&nbsp;</h2>
Um Ihnen eine gezielte Suche nach bestimmten Schulbüchern zu ermöglichen, nutzt der International Textbookcat eine differenzierte Schulbuchsystematik. Diese Systematik setzt sich aus spezifischen Eigenschaften/Facetten zusammen, die Schulbücher im Generellen aufweisen. Somit erlaubt der International TextbookCat innerhalb der Bestände die Suche nach verschiedenen Facetten, die im Folgenden kurz erläutert werden.

<h3>Nutzungsland</h3>
Schulbücher werden nicht grundsätzlich im selben Land eingesetzt, in dem sie erschienen sind. Für die Schulbuchwissenschaft kann aber gerade die Frage nach dem Einsatzort eines Schulbuches besonders interessant sein. Aus diesem Grunde bietet die gezielte Suche nach einem einzelnen Land innerhalb der Facette "Nutzungsland" eine Übersicht über alle dort eingesetzten Schulbücher.
<br />
Anmerkung:
<ul>
<li>Innerhalb der Datenbank Manes wurde das Nutzungsland aus dem Standort der Bibliothek abgeleitet, in der das jeweilige Schulbuch archiviert ist. Die genauen Nutzungsländer der Schulbücher aus dieser Datenbank sollen zukünftig ergänzt werden.</li>
<li>Ziel der Datenbank EDISCO war es, ausschließlich in Italien genutzte Schulbücher zu speichern. In diesem Zusammenhang ist das Nutzungsland in Kombination mit der Datenbank EDISCO grundsätzlich Italien.</li>
</ul>

<h3>Unterrichtsfach</h3>
Um eine datenbankübergreifende Suche nach allen Unterrichtsfächern zu ermöglichen, sind diese nach der International Standard Classification of Education (ISCED) der UNESCO klassifiziert in der Facette zu finden. Der ISCED ist hierarchisch geordnet und ermöglicht so spezialisierte Repräsentationen wie "ISCED 023 - Sprachen", aber auch generelle Repräsentationen wie "ISCED 02 - Kunst und Geisteswissenschaften".
<br />
Vollstandige ISCED-Klassifikation für Unterrichtsfächer:
<div style="height:10em; overflow:auto; border: 2px solid #088">
<pre>
* ISCED-00 	Generic programmes and qualifications
** ISCED-001 	Basic programmes and qualifications 
*** ISCED-0011 	Basic programmes and qualifications 
** ISCED-002 	Literacy and numeracy
*** ISCED-0021 	Literacy and numeracy
** ISCED-003 	Personal skills and  development
*** ISCED-0031 	Personal skills and development
* ISCED-01 	Education
** ISCED-011 	Education
*** ISCED-0111 	Education science
*** ISCED-0112 	Training for pre-school teachers
*** ISCED-0113 	Teacher training without subject specialisation
*** ISCED-0114 	Teacher training with subject specialisation 
* ISCED-02 	Arts and humanities
** ISCED-021 	Arts
*** ISCED-0211 	Audio-visual techniques and media production
*** ISCED-0212 	Fashion, interior and industrial design
*** ISCED-0213 	Fine arts
*** ISCED-0214 	Handicrafts
*** ISCED-0215 	Music and performing arts
** ISCED-022 	Humanities (except languages)
*** ISCED-0221 	Religion and  theology
*** ISCED-0222 	History and archaeology 
*** ISCED-0223 	Philosophy and ethics
** ISCED-023 	Languages
*** ISCED-0231 	Language acquisition
*** ISCED-0232 	Literature and linguistics
* ISCED-03 	Social sciences, journalism and information
** ISCED-031 	Social and behavioural sciences
*** ISCED-0311 	Economics
*** ISCED-0312 	Political sciences and civics
*** ISCED-0313 	Psychology
*** ISCED-0314 	Sociology and cultural studies
** ISCED-032 	Journalism and information
*** ISCED-0321 	Journalism and reporting
*** ISCED-0322 	Library, information and archival studies
* ISCED-04 	Business, administration and law
** ISCED-041 	Business and administration
*** ISCED-0411 	Accounting and taxation
*** ISCED-0412 	Finance, banking and insurance
*** ISCED-0413 	Management and administration
*** ISCED-0414 	Marketing and advertising
*** ISCED-0415 	Secretarial and office work
*** ISCED-0416 	Wholesale and retail sales
*** ISCED-0417 	Work skills
** ISCED-042 	Law
*** ISCED-0421 	Law
* ISCED-05 	Natural sciences, mathematics and statistics
** ISCED-051 	Biological and related sciences
*** ISCED-0511 	Biology
*** ISCED-0512 	Biochemistry
** ISCED-052 	Environment
*** ISCED-0521 	Environmental sciences
*** ISCED-0522 	Natural environments and wildlife
** ISCED-053 	Physical sciences
*** ISCED-0531 	Chemistry
*** ISCED-0532 	Earth sciences
*** ISCED-0533 	Physics
** ISCED-054 	Mathematics and statistics
*** ISCED-0541 	Mathematics
*** ISCED-0542 	Statistics
* ISCED-06 	Information and Communication Technologies (ICTs)
** ISCED-061 	Information and Communication Technologies (ICTs)
*** ISCED-0611 	Computer use
*** ISCED-0612 	Database and network design and administration
*** ISCED-0613 	Software and applications development and analysis
* ISCED-07 	Engineering, manufacturing and construction
** ISCED-071 	Engineering and engineering trades
*** ISCED-0711 	Chemical engineering and processes
*** ISCED-0712 	Environmental protection technology
*** ISCED-0713 	Electricity and energy
*** ISCED-0714 	Electronics and automation
*** ISCED-0715 	Mechanics and metal trades
*** ISCED-0716 	Motor vehicles, ships and aircraft
** ISCED-072 	Manufacturing and processing
*** ISCED-0721 	Food processing
*** ISCED-0722 	Materials (glass, paper, plastic and wood)
*** ISCED-0723 	Textiles (clothes, footwear and leather)
*** ISCED-0724 	Mining and extraction
** ISCED-073 	Architecture and construction
*** ISCED-0731 	Architecture and town planning
*** ISCED-0732 	Building and civil engineering
* ISCED-08	Agriculture, forestry, fisheries and veterinary
** ISCED-081	Agriculture
*** ISCED-0811	Crop and livestock production
*** ISCED-0812	Horticulture
** ISCED-082	Forestry
*** ISCED-0821	Forestry
** ISCED-083	Fisheries
*** ISCED-0831	Fisheries
** ISCED-084	Veterinary
*** ISCED-0841	Veterinary
* ISCED-09	Health and welfare
** ISCED-091	Health
*** ISCED-0911 	Dental studies
*** ISCED-0912 	Medicine
*** ISCED-0913 	Nursing and midwifery
*** ISCED-0914 	Medical diagnostic and treatment technology
*** ISCED-0915 	Therapy and rehabilitation
*** ISCED-0916 	Pharmacy
*** ISCED-0917 	Traditional and complementary medicine and therapy
** ISCED-092	Welfare
*** ISCED-0921	Care of the elderly and of disabled adults
*** ISCED-0922	Child care and youth services
*** ISCED-0923	Social work and counselling
* ISCED-10	Services
** ISCED-101	Personal services
*** ISCED-1011 	Domestic services
*** ISCED-1012 	Hair and beauty services
*** ISCED-1013 	Hotel, restaurants and catering
*** ISCED-1014 	Sports
*** ISCED-1015 	Travel, tourism and leisure
** ISCED-102	Hygiene and occupational health services
*** ISCED-1021 	Community sanitation
*** ISCED-1022 	Occupational health and safety
** ISCED-103	Security services
*** ISCED-1031 	Military and defence
*** ISCED-1032 	Protection of persons and property
** ISCED-104	Transport services
*** ISCED-1041 	Transport services
</pre>
</div>
<br />
Anmerkung:
<ul>
<li>Ein Schulbuch welches nach "ISCED 023 - Sprachen" ausgewiesen wurde, wird automatisch auch in "ISCED 02 - Kunst und Geisteswissenschaften" erfasst.</li>
<li>Die ISCED-Klassifikation hat deutlich mehr Klassen, als der International TextbookCat aktuell bietet. Um ergebnislose Recherchen zu vermeiden, werden nur die Klassen angeboten, für die passende Titel im International TextbookCat vorhanden sind. Eine stetige Erweiterung der Klassen ist bei Hinzufügen neuer Titel in den International TextbookCat also möglich.</li>
</ul>
<br />
Weiterführende Links:
<ul>
<li> <a href="http://www.uis.unesco.org/Education/DOcuments/isced-fields-of-education-training-2013.pdf">http://www.uis.unesco.org/Education/DOcuments/isced-fields-of-education-training-2013.pdf</a></li>
</ul>

<h3>Bildungslevel</h3>
Die Bildungslevel sind in dieser Facette nach der International Standard Classification of Education (ISCED) der UNESCO klassifiziert. Zusätzlich wurden folgende Klassen hinzugefügt, um den Katalog des Georg-Eckert-Instituts besser repräsentieren zu können: "Sonderschule/Förderschule (alle Lernstufen)", "Berufliche Bildungsgänge, alle Lernstufen", "Lehrerbildungseinrichtungen".

<br />
Vollstandige ISCED-Klassifikation für Bildungslevel:
<div style="height:10em; overflow:auto; border: 2px solid #088">
<pre>
* ISCED level 0 – Early childhood education
* ISCED level 1 – Primary education
* ISCED level 2 – Lower secondary education
* ISCED level 3 – Upper secondary education
* ISCED level 4 – Post-secondary non-tertiary education
* Tertiary education
* ISCED level 5 – Short-cycle tertiary education
* ISCED level 6 – Bachelor’s or equivalent level
* ISCED level 7 – Master’s or equivalent level 
* ISCED level 8 – Doctoral or equivalent level
* ISCED level 9 – Not elsewhere classified
* Special school/school catering for pupils with learning difficulties and other special needs (all levels)
* Professional training – all levels
* Teacher training institutions
</pre>
</div>
<br />
Weiterführende Links:
<ul>
<li> <a href="http://www.uis.unesco.org/Education/DOcuments/isced-2011-en.pdf">http://www.uis.unesco.org/Education/DOcuments/isced-2011-en.pdf</a></li>
</ul>

<h3>Dokumenttyp</h3>
Bei den im International TextbookCat zu findenden Beständen handelt es sich nicht ausschließlich um Schulbücher, die für die SchülerInnen gedacht sind. Auch die sogenannten Kranzprodukte, wie Lehrerbände, Arbeitsheft, Lösungshefte etc. sind über diese Facette recherchierbar.

<h2><strong>Datensatzspezifische Schulbucheigenschaften</strong>&nbsp;</h2>
Neben den schulbuchspezifischen Eigenschaften können Sie im International TextbookCat auch nach datensatzspezifischen Eigenschaften suchen, die speziell auf eine ausgewählte Datenbank/Sammlung ausgerichtet sind. Zum jetzigen Zeitpunkt bieten wir Ihnen die Möglichkeit, im Bestand des Georg-Eckert-Instituts nach den Eigenschaften "Schulform" und "Bundesland" zu recherchieren.
<h3>Schulform (GEI)</h3>
Mit Hilfe der Facette "Schulform" können Sie Ihre Suche spezifiziern. Da die verschiedenen Schulformen je nach Land sehr variabel sind, ist diese Facettensuche auf den Bestand an in deutschen Schulen genutzter Schulbücher des Georg-Eckert-Instituts beschränkt.
<h3>Bundesland (GEI)</h3>
Mit Hilfe der Facette "Bundesland" können Sie Ihre Suche innerhalb des Nutzungslandes Deutschland spezifizieren. Zum jetzigen Zeitpunkt bieten wir Ihnen die Suche nach Bundesländern nur für den Schulbuchbestand des Georg-Eckert-Instituts an.

<h2><strong>Statistische Relevanz</strong>&nbsp;</h2>
Bei der Interpretation der Ergebnislisten ist zu beachten, dass nicht alle existierenden Schulbücher im International TextbookCat vorhanden sind. Aussagen wie "In Deutschland werden mehr Schulbücher verfasst als in Spanien" sind daher leider nicht möglich.
<br />
Darüber hinaus sind nicht alle Ausprägungen der schulbuchspezifischen Eigenschaften aus den verschiedenen Katalogen bekannt. Wählen Sie beispielsweise "Berlin" (Kategorie Nutzungsland; Bundesland in Deutschland) an und erhalten keine Schulbuchtreffer aus dem Katalog MANES, so wurde das Nutzungsland möglicherweise nicht in dieser Detailtiefe annotiert. Folglich könnte es also durchaus möglich sein, dass Schulbücher aus der Datenbank MANES speziell in Berlin genutzt werden, auch wenn kein Hinweis darauf zu finden ist.
<br />
Bei der Interpretation von Statistiken, die die Komponente "unbekannt" beinhalten, ist zu beachten, dass ein Schulbuch beispielsweise auch in zwei Bildungslevels benutzt werden und/oder in drei Sprachen verfasst sein kann. Demzufolge sagt das Verhältnis der Werte zu "unbekannt" nichts über die Abdeckung dieser Schulbucheigenschaft aus. Dennoch kann "unbekannt" hilfreich sein, da es anzeigt, ob bestimmte Eigenschaften in einem Katalog grundlegend erfasst werden.
<br />
Fehlerhafte Einträge innerhalb der Kataloge sind zudem nicht auszuschließen.
	
	<div class="divider"><hr></div>
	
	<div class="flyer-page1"></div>
	
	<div class="divider"><hr></div>

	<div class="flyer-page2"></div>

</div>