<?php $this->headTitle('Tutorials'); ?>
<div class="imprint">
	<h1 class="">International TextbookCat Tutorials</h1>

	<h2 class="">Grundlegende Funktionen</h1>
	  <!--span id="take-tour" class="hidden-xs">&nbsp;<a href="#" class="btn btn-primary">Tour</a></span-->
	  <div>Hier werden die grundlegenden Funktionen, die für eine Recherche notwendig sind vorgestellt.</div>
	  
	  <span id="take-tour1" onclick="startBasicTour()" class="hidden-xs">&nbsp;<a href="#" class="btn btn-primary">Tour</a></span>
	  
	<h2 class="">Wissenswertes über den ITBC und dessen Kataloge</h1>
	  <div></div>
	  <span id="take-tour2" onclick="startFactsTour()" class="hidden-xs">&nbsp;<a href="#" class="btn btn-primary">Tour</a></span>

	<h2 class="">Assisitiertes Anlegen eines Accounts</h1>
	  <div>Wir nehmen sie bei der Hand und führen sie durch alle Schritte, die notwendig sind, um einen Account anzulegen.
	  Erst mit einem Account kann man Favoriten verwalten oder Recherchen abspeichern und später fortsetzen.</div>
	  <span><a href="#" class="btn btn-primary">Tour</a></span>

	<h2 class="">Tiefergehende Funktionen</h1>
	  <div>Sie wollen das volle Potential des Tools sofort ausschöpfen? Dann lassen sie sich alle Feature im Detail erklären.</div>
	  <span><a href="#" class="btn btn-primary">Tour</a></span>
</div>
