<?php $this->headTitle('Tutorials'); ?>
<div class="imprint">
	<h1 class="">International TextbookCat Tutorials</h1>

	<h2 class="">Funciones básicas</h1>
	  <!--span id="take-tour" class="hidden-xs">&nbsp;<a href="#" class="btn btn-primary">Tour</a></span-->
	  <div>Aquí se presentan las funciones básicas que son necesarias para realizar una búsqueda.</div>
	  
	  <span id="take-tour1" onclick="startBasicTour()" class="hidden-xs">&nbsp;<a href="#" class="btn btn-primary">Tour</a></span>
	  
	<h2 class="">Datos interesantes sobre el ITBC y sus catálogos</h1>
	  <div></div>
	  <span id="take-tour2" onclick="startFactsTour()" class="hidden-xs">&nbsp;<a href="#" class="btn btn-primary">Tour</a></span>

	<h2 class="">Creación de cuenta</h1>
	  <div>Esto lo guiará a través de todos los pasos necesarios para crear una cuenta. Solo con una cuenta puede administrar favoritos o guardar resultados de búsqueda.</div>
	  <span><a href="#" class="btn btn-primary">Tour</a></span>

	<h2 class="">Funciones avanzadas</h1>
	  <div>¿Quiere aprovechar todo el potencial de la herramienta de inmediato? Entonces puede tener todas las características explicadas en detalle.</div>
	  <span><a href="#" class="btn btn-primary">Tour</a></span>
</div>
